### PR TITLE
fix: make sure that the user can't create a broken table name

### LINKED ISSUE #597: adding databases with a # results in logging out
**What version of EMX2 are you using (see footer)**
8.16.0

**Describe the bug**
After adding a database with a hashtag: git#593 results in being logged out and unable to see the database

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/apps/central/#/'
2. Click on '+'
3. Enter a name with # like git#593
4. see screenshot

**Expected behavior**
Not able to enter # or it should be escaped as special character

**Screenshots**
molgenis-createdb-hashtag-1
molgenis-createdb-hashtag-2

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chromium
 - Version 93.0.4577.82

### PR DESCRIPTION
**Pull request by MaxPostema**
fixes: https://github.com/molgenis/molgenis-emx2/issues/597

### CODE REVIEW

**Review by mswertz — APPROVED** [review]
I think this is correct, see https://github.com/molgenis/molgenis-emx2/blob/54d555ed1d43e07999bd8b0c610f339fd9961a81/backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java#L18

File: apps/central/src/components/SchemaCreateModal.vue [hunk 1]
```diff
@@ -42,6 +42,7 @@
               label="name"
               :defaultValue="schemaName"
               :required="true"
+              :errorMessage="validate(schemaName)"
```
Comment (chinook25) [inline apps/central/src/components/SchemaCreateModal.vue:45]: computed errorMessage so we don't have to call the same function twice?
