### PR TITLE
fix: should not be able to create column in superclass with same name as in one or more subclasses

### LINKED ISSUE #2295: (Repeated) variables (values) tables are broken
**What version of EMX2 are you using (see footer)**
[8.177.0](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.177.0).

**Describe the bug**
Variables, Repeated Variables and Variable Values tables broken (only in ATHLETE staging area). Changing the name of the _since version_ and _until version_ columns in the 'All Variables' table fixes it.

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/ATHLETE/tables/#/
2. Click on 'Variables' table

**Screenshots**
Screenshot 2023-05-11 at 15 21 34

**Test data**
[ATHLETE_bug.zip](https://github.com/molgenis/molgenis-emx2/files/11452663/ATHLETE_bug.zip)

### PR DESCRIPTION
**Pull request by mswertz**
closes #2295 (or to be specific, wil prevent that database can go into a state causing this bug).

How to test:
* create a data model with inheritance. E.g. subclass table contains 'sinceVersion'
* then try change data model where you add this same column name to parent table.

Previously: this would be possible but leading to #2295 
With this fix: error message is produced and such data model change prohibited

Alternatives considered:
- we could have done this in Java but that would require to first load all schemas into java and then iterate through it. That is expensive
- we could have changed metadata with extra 'root table' column so one can find all columns linked to same class hierarchy without recursion. Metadata change would have required a migration. Might be something for the list of '9.x' changes.

### CODE REVIEW

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java [hunk 1]
```diff
@@ -71,6 +76,30 @@ public void testExtends() {
...
+    }
+
+    // try to alter name in superclass that already exists in any subclass IN OTHER SCHEMA
+    try {
+      person.getMetadata().add(column("title").setType(DATE));
+      fail("should fail: cannot add column in superclass to name that already exists in subclass");
+    } catch (MolgenisException e) {
+      System.out.println("Errored correctly:\n" + e);
+    }
+
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java:102]: same test for sub class ? , test for n level inheritance ?

Comment (mswertz) [reply backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java:102]: Motivation for second test is that I wanted to test both multi-level AND cross schema inheritance.

Comment (connoratrug) [reply backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java:102]: This is not clear form the test name. In general; create i test for each case and use a descriptive name ( optionally add description ). This not only helps with code review and extending / removing  tests but is show when test fails in CI context

Comment (mswertz) [reply backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java:102]: The comment above was explanatory if you read the uppercase letters. 

I don't feel to refactor the whole test suite now to be split in all kind of little tests now. Because, until now we have not discussed changing our pattern of test writing with the desire to split in little tests. I would like to be consistent.

I might be tempted to try that with you in a new test suite. However, I feel this will result in code verbosity as well as in runtime overhead (if applied to total test suite, it would 5-10x the set) which is one of the reasons I have not done this so far. But maybe we like it.

**Comment by mswertz** [comment]
@connoratrug can you please comment on the functionality of this PR?

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java (hunk 1 above)
Comment (mswertz) [reply backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java:102]: Hmm, having slept over it I noticed what might be the real issue: the fail message was the same. Updated it.

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadata.java [hunk 2]
```diff
@@ -55,6 +55,9 @@ private static SqlTableMetadata addTransaction(
                   + ": column exists in inherited class "
                   + tm.getInherit());
         }
+        // check no subclass has column with this name
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadata.java:58]: no need for code comment , the method name explains it's function

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadata.java [hunk 3]
```diff
@@ -183,6 +186,10 @@ private static SqlTableMetadata alterColumnTransaction(
     }
 
     validateColumn(newColumn);
+    if (!columnName.equals(column.getName())) {
+      // check no subclass has column with this name
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadata.java:190]: same

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadataExecutor.java [hunk 4]
```diff
@@ -396,4 +395,52 @@ private static void executeEnableSearch(DSLContext jooq, TableMetadata table) {
 
     createSearchTrigger(jooq, table, table.getTableName());
   }
+
+  static void checkNoColumnWithSameNameExistsInSubclass(
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadataExecutor.java:399]: would have expected a model check instead of check in db , looks oke , but large complex query like this is hard to review / maintain / extend / fix . My not use the (java)model for this check

File: backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java [hunk 5]
```diff
@@ -61,6 +61,10 @@ public static void before() throws Exception {
         // disable because of parallism issues .and(MOLGENIS_INCLUDE_CATALOGUE_DEMO, "true")
         .execute(() -> RunMolgenisEmx2.main(new String[] {}));
 
+    // wait until started, is this worth it or should we go back to simply
+    // 'MolgenisWebservice.start(port)'?
+    Thread.sleep(5000);
```
Comment (connoratrug) [inline backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java:66]: this looks dodgy , a test that needs to wait for 5 seconds ..

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadataExecutor.java (hunk 4 above)
Comment (mswertz) [reply backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadataExecutor.java:399]: I initially used the Java api however that turned out to be slow and could become impossible slow, because it requires to iteratively retrieve ALL schemas in the database (which might many!!!) and then iterate through all inherited tables (which it cannot know from the parent schema). This query queries the metadata model as it is stored in the database so we can make use of postgresql filter capability.

File: backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java (hunk 5 above)
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java:66]: yes, this shouldn't be here.
