### PR TITLE
fix: fix cohort cart short description toggle and empty value case

### LINKED ISSUE #2561: Cohort list card without description is show as "undefined..."
**What version of EMX2 are you using (see footer)**
8.207.1

**Describe the bug**
Cohort listing card for cohort with empty description is shown as 'undefined...' when viewed in medium screen size mode 

**To Reproduce**
1. Go to 'https://umcgresearchdatacatalogue.nl/UMCG/ssr-catalogue/cohorts/?page=4'
2. Seize screen size to medium with 
4. look at NeoLines 

**Expected behavior**
empty / black instead of undefined ...

**Screenshots**

Screenshot 2023-07-26 at 12 32 38

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #2561

### CODE REVIEW

File: apps/nuxt3-ssr/components/CohortCard.vue [hunk 1]
```diff
@@ -85,21 +76,18 @@ const isShowingMobileMoreText = computed(() => {
...
+      <p v-if="cohort?.description" class="text-body-base mt-5 block xl:hidden">
         {{
-          isShowingMobileMoreText
-            ? cohort?.description
-            : `${cohort?.description?.substring(
-                0,
-                mobileShowMoreTextLength
-              )}...`
+          truncate
+            ? `${cohort?.description?.substring(0, cutoff)}...`
```
Comment (mswertz) [inline apps/nuxt3-ssr/components/CohortCard.vue:82]: for now okay, but don't we want to use a component for this that truncates so we can easily do it everywhere?

**Review by mswertz — APPROVED** [review]

File: apps/nuxt3-ssr/components/CohortCard.vue (hunk 1 above)
Comment (connoratrug) [reply apps/nuxt3-ssr/components/CohortCard.vue:82]: yes, good idea , but still suggest we do this bug fix first
