### PR TITLE
fix: tw table-explorer edit mode

### LINKED ISSUE #5478: Edit mode styling is broken
### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

13.49.3

### Description

see: 

Image

### Reproduction steps

1. Go to 'https://emx2.dev.molgenis.org/apps/ui/pet%20store/Pet'
2. Sign in the see edit mode

### Expected behaviour

actions should float on top of fist column

### System configuration

- Device: 
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by connoratrug**
### What are the main changes you did
Instead of adding a column ( produces 'invalid' table html), add a slot to the column. When in edit mode, pass the actions to the first column. This swaps a complex table layout ( table layout in already complex ) for a complex cell layout ( issue is resolved more locally)

add remove intermediate component as its no longer needed in this setup 

Closes #5478 

- explain what you changed and essential considerations.

### How to test
- explain here what to do to test this (or point to unit tests)

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: apps/tailwind-components/app/components/table/CellEMX2.vue [hunk 1]
```diff
@@ -1,5 +1,6 @@
 <template>
-  <TableBodyCell>
+  <td class="p-2.5 border-b border-gray-200 min-h-8 text-left truncate">
+    <slot name="row-actions"></slot>
```
Comment (connoratrug) [inline apps/tailwind-components/app/components/table/CellEMX2.vue]: placeholder for row actions

File: apps/tailwind-components/app/components/table/TableEMX2.vue [hunk 2]
```diff
@@ -147,7 +98,46 @@
...
+                    :id="`table-emx2-${schemaId}-${tableId}-${getRowId(
+                      row
+                    )}-delete-row-button`"
+                    :icon-only="true"
+                    type="inline"
+                    icon="edit"
+                    size="small"
+                    label="edit"
+                    @click="onShowEditModal(row)"
+                    :aria-controls="`table-emx2-${schemaId}-${tableId}-modal-edit`"
```
Comment (davidruvolo51) [inline apps/tailwind-components/app/components/table/TableEMX2.vue]: And encodeURI here
