### PR TITLE
fix: ontology filter doesn't update when wells are removed. closes #1795

### LINKED ISSUE #1795: FilterSidebar does not sync filterWells state with ontologyFilter
**What version of EMX2 are you using (see footer)**
[8.125.1]

**Describe the bug**
When the filter well above the table is used to remove a filter set via a ontology_array filter the 
ontologyInput status is not updated ( remains checked )

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/apps/molgenis-components/#/component/FilterSidebar'
2. Click on tags filter colors to enable all the color filters 
3. Scroll up to the filter wells and use the 'x' to remove the color:red filter
4. ontologyInput still has the color.red selected

**Expected behavior**
Filter wells to be in sync with filter state and ui

### PR DESCRIPTION
**Pull request by mswertz**
Issue also applied to ref_array

closes #1795

### CODE REVIEW

File: apps/molgenis-components/src/components/forms/InputOntology.vue [hunk 1]
```diff
@@ -430,10 +433,12 @@ export default {
...
     },
-    value() {
-      if (this.terms.size > 0) {
-        this.applySelection(this.modelValue);
-      }
+    modelValue: {
+        deep: true,
+        handler() {
+          this.applySelection(this.modelValue);
+          this.key++;
```
Comment (connoratrug) [inline apps/molgenis-components/src/components/forms/InputOntology.vue:440]: why key++ , suggest to add code comment

**Review by connoratrug — APPROVED** [review]

**Comment by mswertz** [comment]
[Fix: ontology input doesnt update when you close filter well](https://trello.com/c/hwa7Erpa/575-fix-ontology-input-doesnt-update-when-you-close-filter-well)
