### PR TITLE
fix: column position was removed on update using graphql api

### LINKED ISSUE #1495: Change in table prop results in change in column order
**What version of EMX2 are you using (see footer)**
8.110

**Describe the bug**
Using a gql command to update a table meta data prop ( for example field type) results in a change of column order ( the changed field becomes the last column.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. run a change command ```mutation{change(columns: {table: \"Pets\", name: \"name\", columnType: \"TEXT\"}){message}} ```
3. column name is now the last column

**Expected behavior**
Column order does not change

### PR DESCRIPTION
**Pull request by mswertz**
closes #1495

### CODE REVIEW

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadata.java [hunk 1]
```diff
@@ -230,12 +230,12 @@ private static SqlTableMetadata alterColumnTransaction(
...
     // update the metadata so we can use it for new keys and references
     if (column.getPosition() == null) {
-      column.setPosition(tm.columns.get(columnName).getPosition());
+      newColumn.setPosition(tm.columns.get(columnName).getPosition());
     }
     // remove the old
     tm.columns.remove(columnName);
     // add the new
-    tm.columns.put(column.getName(), column);
+    tm.columns.put(column.getName(), newColumn);
```
Comment (mswertz) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadata.java:238]: this is amazing that this error still existed
