### PR TITLE
fix: 4368 Dynamic ontology value render to keep consistent indentation in key value lists 

### LINKED ISSUE #4368: fix(catalogue): the alignment of the fields under Access Conditions is weird and we've had comments from others about it.
The Data use conditions and Release type fields under Access Conditions on the cohort page are incorrectly aligned (both vertically and horizontally).

eg https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/all/cohorts/testCohort2

image

We've had comments from external feedback-givers about alignment of fields, so this is definitely something which people notice.

### PR DESCRIPTION
**Pull request by connoratrug**
What are the main changes you did:

- Consistently render ontology fields as ontology
- Dynamic ontology value render to keep consistent indentation in key value lists
  - case single item, render as item
  - case list ( no depth ), render as list
  - case tree, render as a tree
- fix description info icon hover color in case of inverted background
- render description if set for ontology items ( regardless of case)
- indent value section in case of key/value single column layout

Closes #4368

how to test:
see https://github.com/molgenis/molgenis-emx2/issues/4368
todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Review by mswertz — COMMENTED** [review]
I approve but I notice my css skills are lacking

File: apps/nuxt3-ssr/components/CatalogueListItem.vue [hunk 1]
```diff
@@ -0,0 +1,89 @@
+<script setup lang="ts">
+import type { IDefinitionListItem } from "~/interfaces/types";
+
+withDefaults(
+  defineProps<{
+    item: IDefinitionListItem;
```
Comment (chinook25) [inline apps/nuxt3-ssr/components/CatalogueListItem.vue:6]: Why do you still put script on top for new files?

**Review by mswertz — APPROVED** [review]
