### PR TITLE
fix: toggle oidc login via settings

### LINKED ISSUE #4587: OIDC SignIn button not shown in case landing page resolves to an App
### Have you checked if this issue already exists?

- [X] yes

### Molgenis EMX2 version

11.41.4

### Description

OIDC sign in button not available after version [11.33.2](https://github.com/molgenis/molgenis-emx2/releases/tag/v11.33.2) in case the landing page of the server is an app (ERN Dashboard, or Directory App). 
SignUp SignIn buttons are shown. 

When navigating to apps/central the single (OIDC) Signin button is shown and you can login via OIDC

See also discussion in:
https://molgenisdev.slack.com/archives/C057JRKLUKG/p1734682958999559

@harmbrugge has made a fix for this, but unfortunately this does not solve the issue.

### Reproduction steps

1. Goto https://emx2.dev.molgenis.org

### Expected behaviour

OIDC signIn button should be also shown on the landing page in case it's an App.

### System configuration

- Device: 
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by connoratrug**
### What are the main changes you did
- Keep state in settings ( like the other settings)
- only check props once ( on system start )
- always include isOidcEnabled setting on settings request

Closes #4587

### How to test
- explain here what to do to test this (or point to unit tests)

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlDatabaseFieldFactory.java [hunk 1]
```diff
@@ -148,6 +148,8 @@ public GraphQLFieldDefinition.Builder settingsQueryField(Database database) {
                           setting ->
                               selectedKeys.isEmpty() || selectedKeys.contains(setting.getKey()))
                       .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
+              selectedSettings.put(
+                  Constants.IS_OIDC_ENABLED, String.valueOf(database.isOidcEnabled()));
```
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlDatabaseFieldFactory.java:152]: right

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java [hunk 2]
```diff
@@ -226,38 +230,6 @@ public void init() { // setup default stuff
...
   }
 
-  private void initOidc() {
-    // oidc settings takes priority over env variables
-    String isOidcEnabledSetting = getSetting(Constants.IS_OIDC_ENABLED);
-    if (isOidcEnabledSetting != null) {
-      this.isOidcEnabled = Boolean.parseBoolean(isOidcEnabledSetting);
-    } else {
-      Object envSetting =
-          EnvironmentProperty.getParameter(Constants.MOLGENIS_OIDC_CLIENT_ID, null, STRING);
```
Comment (mswertz) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java:236]: I think we should at some point have some way to find out about oidc errors but this is probably not the way.

**Review by mswertz — APPROVED** [review]
code and approach looks okay. But how to test?

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java [hunk 3]
```diff
@@ -226,38 +230,6 @@ public void init() { // setup default stuff
...
-      if (envSetting != null) {
-        this.setSetting(Constants.IS_OIDC_ENABLED, "true");
-        this.isOidcEnabled = true;
-      }
-    }
-    if (!this.isOidcEnabled) return;
-
-    // check if OIDC settings are complete otherwise log error and set to false
-    if (!isValidOidcSettings()) {
```
Comment (harmbrugge) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java:245]: So we don't check if OIDC settings are complete, when enabled? This is fine by me, but I made it because it was requested

**Review by harmbrugge — COMMENTED** [review]
Always hetting the oidc enabled via settings looks fine, but don't we want a check to see if the settings are complete before enabling it?

**Review by harmbrugge — APPROVED** [review]

**Review by dtroelofsprins — APPROVED** [review]
Locally tested:

isOidcEnabled = false:
- [x] apps/central => SignUp, SignIn buttons
- [x] schema level => SignUp, SignIn buttons

isOidcEnabled = true:
- [x] apps/central => only SignIn button
- [x] schema level => only SignIn button
