### PR TITLE
fix: file columns are emptied when updating

### LINKED ISSUE #865: Uploaded files in columnType 'file' that are saved disappear when saving a form again
**What version of EMX2 are you using (see footer)**
8.35.3

**Describe the bug**
Uploaded files in columnType 'file', e.g. 'logo' in table 'Cohorts' disappear when data is saved via forms again.

**To Reproduce**
1. Go to an emx2 server
2. Load a catalogue dataset
3. Save a logo under a cohort
4. re-enter data for the Cohort and save again: the logo has disappeared.

### PR DESCRIPTION
**Pull request by mswertz**
closes #865 

bug:
- when updating a record in web forms file fields where 'emptied' on update

expected behavior:
- when I inserted a record with a file and then update that record and didn't touch the file input then my file should still be set

bug:
- when uploading a zip file that includes the file attachments, the files are actually not uploaded (this feature was simply never implemented!)

expected:
- when I download data from one server using zip (not Excel!) and upload into another all file attachments should be included

[x] support update without and with deleting when updating via the web frontend
[ ] support upload of csv including file attachments (so you can upload a downloaded copy from another server)

I propose to first complete the first feature and then create a new PR for the import/export

### CODE REVIEW

**Review by connoratrug — CHANGES_REQUESTED** [review]
Can not edit the row 
- create table with non-file type and file-type columns
- add a row with file and non file data
- edit the row , only edit non file data , save row 
-
Screenshot 2022-01-14 at 11 22 57

**Comment by mswertz** [comment]
I have removed the MG_DELETE_FILE hack. Backend can distinguish updates (that need processing) from non-updates (that needs ignored) because 
* in case of a non-update a json object {} is submitted with the file metadata (backend sees this as a Map)
* in case of an update the input is either 'null' or a file upload (backend sees this as either 'null' or file upload Part

File: backend/molgenis-emx2/src/main/java/org/molgenis/emx2/BinaryFileWrapper.java [hunk 1]
```diff
@@ -11,6 +11,12 @@
   // these we calculate on construction
   String mimetype;
   String extension = "";
+  // this is used to skip file updates
```
Comment (connoratrug) [inline backend/molgenis-emx2/src/main/java/org/molgenis/emx2/BinaryFileWrapper.java:14]: needs more context

File: backend/molgenis-emx2/src/main/java/org/molgenis/emx2/BinaryFileWrapper.java [hunk 2]
```diff
@@ -11,6 +11,12 @@
...
+  boolean skip = false;
```
Comment (connoratrug) [inline backend/molgenis-emx2/src/main/java/org/molgenis/emx2/BinaryFileWrapper.java:15]: In general i do not think its very nice to have this stateful bool, but i guess its kind of the java way, could it not be a function that calculates the bool response based on the state ( instead of a extra state flag)

**Review by connoratrug — APPROVED** [review]
Issue is fixed
