### PR TITLE
fix: clone button didn't work. closes #1032

### LINKED ISSUE #1032: Copy row function does not copy any data
**What version of EMX2 are you using (see footer)**
8.54.1

**Describe the bug**
The copy row function does not copy any data, it delivers an empty form.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/Conception-test/catalogue/#/Cohorts' log in as admin
2. Click on columns, data all
3. See that test contains data in columns.
4. Copy test row
5. You get an empty form

### PR DESCRIPTION
**Pull request by mswertz**
closes #1032

### CODE REVIEW

**Comment by mswertz** [comment]
[fix: row clone button](https://trello.com/c/eE3FhNI1/420-fix-row-clone-button)

File: apps/styleguide/src/tables/RowEditModal.vue [hunk 1]
```diff
@@ -269,12 +269,7 @@ export default {
         let defaultValue = {};
         this.tableMetadata.columns.forEach((column) => {
           // skip key in case of clone and visible
-          if (
-            data[column.id] &&
-            (!this.clone ||
-              column.key != 1 ||
-              !this.visibleColumns.includes(column.name))
-          ) {
+          if (data[column.id] && (!this.clone || column.key != 1)) {
```
Comment (connoratrug) [inline apps/styleguide/src/tables/RowEditModal.vue:272]: what is the meaning of column.key and what is the meaning of the magic '1' value ?

Comment (mswertz) [reply apps/styleguide/src/tables/RowEditModal.vue:272]: See user guide: https://molgenis.github.io/molgenis-emx2/#/molgenis/use_schema?id=key

key indicates whether column is part of a unique constraint. Key=1 means primary key.
In other words: columns that are part of primary key should not be cloned because must be unique.

Comment (connoratrug) [reply apps/styleguide/src/tables/RowEditModal.vue:272]: in that case replace the 1 with meaningful constant PRIMARY_KEY , and the reason for not including the primary key could be added in a comment line

Comment (mswertz) [reply apps/styleguide/src/tables/RowEditModal.vue:272]: that comment indeed exists on line 271. Because that already exists you don't see in track changes. I improve the comment for those who don't know yet that key=1 means primary key. I don't see added value of meaningful constant (adding extra code, unnecessary obfuscation) because in schema manual we also simply use '1'.
