### PR TITLE
fix: settings and JWT default secret

### LINKED ISSUE #1856: Admin settings are not saved
**What version of EMX2 are you using (see footer)**
8.131.0

**Describe the bug**
Admin settings are not saved properly

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/apps/central/#/admin/settings'
2. Log in as admin
3. Change or add a setting.
4. Refresh the page, settings should still be correct
5. Log out
6. Log in again as admin
7. Settings are reset to default :(

**Expected behavior**
Settings are properly saved even when the admin logs out.

**Desktop (please complete the following information):**
 - OS: Windows 11 / OSX
 - Browser: Firefox / Chrome

**Additional notes:**
 - Seems to be broken by https://github.com/molgenis/molgenis-emx2/pull/986

### PR DESCRIPTION
**Pull request by mswertz**
closes #1856

### CODE REVIEW

**Review by chinook25 — APPROVED** [review]

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java [hunk 1]
```diff
@@ -168,6 +169,18 @@ public void init() { // setup default stuff
       if (getSetting(Constants.PRIVACY_POLICY_TEXT) == null) {
         this.setSetting(Constants.PRIVACY_POLICY_TEXT, Constants.PRIVACY_POLICY_TEXT_DEFAULT);
       }
+
+      String key =
+          (String)
+              EnvironmentProperty.getParameter(Constants.MOLGENIS_JWT_SHARED_SECRET, null, STRING);
+      if (key == null) {
+        key = getSetting(Constants.MOLGENIS_JWT_SHARED_SECRET);
```
Comment (joerivandervelde) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java:177]: getSetting(Constants.MOLGENIS_JWT_SHARED_SECRET) always returns null after server restart, even if there is a key present. This results in a new key being generated and thereby invalidating existing tokens.

**Review by joerivandervelde — CHANGES_REQUESTED** [review]
Does not seem to work as intended yet, see comment in code

**Review by joerivandervelde — APPROVED** [review]
Problem is indeed fixed
