### PR TITLE
Fix/show false bool val

### LINKED ISSUE #646: catalogue radio button true/false options are not shown in datasources and databank details
**What version of EMX2 are you using (see footer)**
8.20.5

**Describe the bug**
While editing or updating a datasource or databank the true or false options like 'accessSubjectDetails' or not shown in the datasources/databanks detail overiew

**To Reproduce**
1. Go to 'https://minerva.molgeniscloud.org/Minerva/catalogue/#/datasources'
2. Click on 'pencil to edit datasource'
3. edit 'accessSubjectDetails' to TRUE
4. Save datasources
5. Click on the Datasources you just edited and you will notice accessSubjectDetails is missing

**Expected behavior**
Expect to see the TRUE value I just added

**Screenshots**

molgenis-8 20 5_true-false_radio_1

molgenis-8 20 5_datasource-detail

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chromium
 - Version 94.0.4606.81

### PR DESCRIPTION
**Pull request by connoratrug**
Fix issue where field value of type boolean is not shown when set to false 

- Extract render loop form vue template
- Spit into components
- Fix boolean render
- Fix File n/a render

Closes #646

### CODE REVIEW

**Comment by connoratrug** [comment]
[Fix 646 boolean not shown of false in resource detail view](https://trello.com/c/WzXq3hLv/309-fix-646-boolean-not-shown-of-false-in-resource-detail-view)

File: apps/catalogue/src/components/detailView/OntologyFieldValue.vue [hunk 1]
```diff
@@ -0,0 +1,29 @@
+<template>
+  <ObjectDisplay
+    :class="'font-weight-bold mr-2 mb-2 badge bade-lg badge-' + color"
+    :data="data"
+    :metaData="metaData"
+  />
+</template>
+
+<script>
+import { ObjectDisplay } from "@mswertz/emx2-styleguide";
```
Comment (mswertz) [inline apps/catalogue/src/components/detailView/OntologyFieldValue.vue:10]: You could here perfectly make use of vue inheritance. Why don't you? 

Secondly, should we not move this component to styleguide module, because it is basically the mirror of the *Input components there.

File: apps/catalogue/src/views/ResourceDetailsView.vue [hunk 2]
```diff
@@ -1,130 +1,30 @@
 <template>
-  <div class="container bg-white" id="_top" v-if="row">
```
Comment (mswertz) [inline apps/catalogue/src/views/ResourceDetailsView.vue:2]: I originally chose 'row' with the idea that we could generalize this to all types of rows.

File: apps/catalogue/src/views/ResourceDetailsView.vue [hunk 3]
```diff
@@ -155,118 +63,49 @@ export default {
...
+          if (isHeading(item)) {
+            accum.push({ meta: item, fields: [] });
           } else {
-            return this.flattenObject(v);
+            if (!accum.length) {
+              accum.push({ meta: item, fields: [] });
+            }
+            accum.at(-1).fields.push({
+              meta: { ...item, primaryTableKey: this.primaryTableKey },
+              value: this.resourceData[item.name],
```
Comment (mswertz) [inline apps/catalogue/src/views/ResourceDetailsView.vue:87]: after pull request #672 this should change to item.id ?

File: apps/catalogue/src/views/ResourceDetailsView.vue [hunk 4]
```diff
@@ -155,118 +63,49 @@ export default {
...
-      if (
-        col.columnType == "REF_ARRAY" ||
-        col.columnType == "MREF" ||
-        col.columnType == "REFBACK" ||
-        col.columnType == "ONTOLOGY_ARRAY"
-      ) {
-        return row[col.name].map((v) => {
-          if (col.refLabel) {
-            return this.applyJsTemplate(col.refLabel, v);
+    sections() {
```
Comment (mswertz) [inline apps/catalogue/src/views/ResourceDetailsView.vue:69]: nice idea, now you can hide complete sections in case all items are NA?

File: apps/catalogue/src/views/ResourceDetailsView.vue [hunk 5]
```diff
@@ -155,118 +63,49 @@ export default {
...
-        if (object[key] === null) {
-          //nothing
-        } else if (typeof object[key] === "object") {
-          result += this.flattenObject(object[key]);
-        } else {
-          result += "." + object[key];
+    primaryTableKey() {
+      return this.tableMetadata.columns.reduce((accum, col) => {
+        if (col.key == 1 && this.resourceData[col.name]) {
+          accum[col.name] = this.resourceData[col.name];
```
Comment (mswertz) [inline apps/catalogue/src/views/ResourceDetailsView.vue:99]: also col.id after #672

File: apps/catalogue/src/components/detailView/OntologyFieldValue.vue [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+export default {
+  name: "OntologyFieldValue",
+  components: { ObjectDisplay },
+  props: {
```
Comment (mswertz) [inline apps/catalogue/src/components/detailView/OntologyFieldValue.vue:14]: I would probably call this prop 'value', why did you chose 'data'?

File: apps/catalogue/src/components/detailView/SectionCard.vue [hunk 7]
```diff
@@ -0,0 +1,68 @@
+<template>
+  <div class="mt-0">
+    <a v-if="showCardHeader" href="#_top" class="float-right text-white"
+      >back to top</a
```
Comment (mswertz) [inline apps/catalogue/src/components/detailView/SectionCard.vue:4]: formatting error

**Review by mswertz — APPROVED** [review]
This is a beautiful pull request. While I prefer my code to be less spread out over files, this is really nicely done.

I have a few comments below

**Comment by connoratrug** [comment]
> This is a beautiful pull request. While I prefer my code to be less spread out over files, this is really nicely done.
> 
> I have a few comments below

it is 'spead' across single file components to enable composition ( reuse without inheritance), vue uses a file per component standerd

File: apps/catalogue/src/components/detailView/OntologyFieldValue.vue (hunk 1 above)
Comment (connoratrug) [reply apps/catalogue/src/components/detailView/OntologyFieldValue.vue:10]: "not move this component to styleguide" yes , we should but wanted to wait to discuss differences ( if any) between rendering values en a table cell of read only card , or other context .. , propose to have a separate PR as there may be some edge cases  

'vue inheritance' makes it hard to see what is going on an avoid state bugs, suggest using shared lib and have explicit component api via props

File: apps/catalogue/src/views/ResourceDetailsView.vue (hunk 2 above)
Comment (connoratrug) [reply apps/catalogue/src/views/ResourceDetailsView.vue:2]: row confused me in this context as the context is a single row , and we are redering row's of cards and list items , suggest to use row and column when referring to tables, and use section and field ( or something else , but not row and column) when the context is a cards ( data object)

File: apps/catalogue/src/views/ResourceDetailsView.vue (hunk 3 above)
Comment (connoratrug) [reply apps/catalogue/src/views/ResourceDetailsView.vue:87]: yes , the resourceData is a map created from a 'row' and the 'name' is used as key , if the key changes to id , this should be updated

File: apps/catalogue/src/views/ResourceDetailsView.vue (hunk 4 above)
Comment (connoratrug) [reply apps/catalogue/src/views/ResourceDetailsView.vue:69]: yes  , i would suggest doing that , did not add it to the PR to keep original behaviour , but this setup allow to easily implement doing things to entire sections.

File: apps/catalogue/src/views/ResourceDetailsView.vue (hunk 5 above)
Comment (connoratrug) [reply apps/catalogue/src/views/ResourceDetailsView.vue:99]: yes

File: apps/catalogue/src/components/detailView/OntologyFieldValue.vue (hunk 6 above)
Comment (connoratrug) [reply apps/catalogue/src/components/detailView/OntologyFieldValue.vue:14]: because its paired with 'data' , meta -> data
