### PR TITLE
fix(directory): collection count

### LINKED ISSUE #3016: Directory App: Counting collections/sub-collections goes wrong
**What version of EMX2 are you using (see footer)**
v10.3.2

**Describe the bug**
The number of collections in the search results is wrong. The count is the total number of collections

**To Reproduce**
1. Go to 'https://bbmri-emx2-test.molgeniscloud.org'
2. Click on Directory
3. Look at the search results
4. Number of collections = 3227 and number of sub-collections = 1098
5. Go to tables and open the Collections table => total amount of collections = 3227 

**Expected behavior**
The number of collections and number of sub-collections in the search results should add up to the total amount of collections in the Collections Table (excluding the withdrawn, see other issue).

**Screenshots**
https://bbmri-emx2-test.molgeniscloud.org/Directory/directory/#/catalogue vs https://directory.bbmri-eric.eu/menu/main/app-molgenis-app-biobank-explorer?#/catalogue

### PR DESCRIPTION
**Pull request by chinook25**
Make sure collections+subcollections add up to total number of collections in the collections table.
fixes #3016

### CODE REVIEW

File: apps/directory/src/stores/biobanksStore.js [hunk 1]
```diff
@@ -199,6 +193,13 @@ export const useBiobanksStore = defineStore("biobanksStore", () => {
       .flatMap((collection) => collection.sub_collections).length;
   });
 
+  const biobankCardsCollectionCount = computed(() => {
+    const totalCount = biobankCards.value
+      .filter((bc) => bc.collections)
+      .flatMap((biobank) => biobank.collections).length;
```
Comment (mswertz) [inline apps/directory/src/stores/biobanksStore.js:199]: I don't mind to do it this way, but this is not something the graphql query can easily produce?

**Review by dtroelofsprins — CHANGES_REQUESTED** [review]
I've used the data from https://bbmri-emx2-test.molgeniscloud.org to test this PR as the Demo dataset turned out to be not sufficient enough.
https://preview-emx2-pr-3131.dev.molgenis.org/DieuwkesTest/directory/#/catalogue

Counts are OK when no filters are applied.
When using for example the Categories filter => Rare disease, collections count gets negative... Total count of the subcollections is in this case also wrong.

Did'nt reviewed the code.

File: apps/molgenis-components/src/queryEmx2/queryEmx2.ts [hunk 2]
```diff
@@ -3,29 +3,32 @@
...
-  limits = {};
-  orderings = {};
+  limits: Record<string, number> = {};
+  orderings: Record<string, { column: string; direction: "asc" | "dsc" }> = {};
   findInAllColumns = "";
-  page = {};
+  page: Record<string, any> = {};
   aggregateQuery = false;
+  type = "";
+  orCount = 0;
```
Comment (chinook25) [inline apps/molgenis-components/src/queryEmx2/queryEmx2.ts:22]: note: these 2 variables where not initialized originally, which was a bug (though I don't know the symptoms).

**Review by dtroelofsprins — APPROVED** [review]
For the filters etc that I've tested the counts look really good now! Subcollections counts are going OK and also applying filters results in comparable results with the current EMX1 Directory App.

Until now I found one set of filters that results in different counts: Country Austria and Available for commercial Use. Looking at the actual data it seems that the current EMX1 is missing one biobank. But need to dive a little deeper into it. Nevertheless it is then probably more a filtering issue than that there is something wrong with the counts.

NB. Only did a functional review, no code review.

File: apps/directory/src/stores/biobanksStore.js (hunk 1 above)
Comment (esthervanenckevort) [reply apps/directory/src/stores/biobanksStore.js:203]: Wouldn't it be easier to count collections and subcollections by checking if the parent is set?

**Review by esthervanenckevort — APPROVED** [review]
Functional test was done by Dieuwke and passed the requirement, just wondering if the way of counting isn't overly complex. A collection is a subcollection if it has a parent, otherwise it is a (root) collection. Can't we use that fact to simplify the counting?

File: apps/directory/src/stores/biobanksStore.js (hunk 1 above)
Comment (chinook25) [reply apps/directory/src/stores/biobanksStore.js:203]: I'd say that would be on par, since it would need more data retrieval and similar filtering. This was easier to implement with the existing code. If you'd rather have it changed, let me know.

Comment (esthervanenckevort) [reply apps/directory/src/stores/biobanksStore.js:203]: If that's the case then leave it as is. No need to change.
