### PR TITLE
fix: 4249 set path to new app folder

### LINKED ISSUE #4249: fix(directory): App contains links to images in molgenis-app-biobank-explorer folder
**What version of EMX2 are you using (see footer)**
v11.13.0

**Describe the bug**
The Directory App contains by default links to files in the EMX1 Directory repo. This might eventually cause unexpected issues.
The links are in molgenis-emx/apps/directory/src/property-config/initialLandingpage.js. It seems that the files are already also available in molgenis-emx2/aps/directory/public/img apps/directory/public/img

**Expected behavior**
The references to the files in the EMX1 version of the Directory App should be replaced by one in the molgenis-emx2 repo.

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #4249

What are the main changes you did:
- updated the links as suggested in issue 

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: apps/directory/src/property-config/initialLandingpage.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ const initialLandingpage = {
   css: {
     pageHeader: {
       backgroundStyle:
-        'background: url("https://github.com/molgenis/molgenis-app-biobank-explorer/blob/master/public/img/bacteria.jpg?raw=true");background-size: cover;height: 30rem;width: 75%;border-radius: 1rem; color: #fff;text-align: center;',
+        'background: url("https://github.com/molgenis/molgenis-emx2/blob/master/apps/directory/public/img/bacteria.jpg?raw=true");background-size: cover;height: 30rem;width: 75%;border-radius: 1rem; color: #fff;text-align: center;',
```
Comment (mswertz) [inline apps/directory/src/property-config/initialLandingpage.js:66]: I would prefer to use a internally stored file, i.e., one that is served via the 'apps' folder i.e. using address `/directory/public/img/bacteria.jpg`. Otherwise this breaks if we would change github or if it is run behind a firewall or offline.

**Review by mswertz — CHANGES_REQUESTED** [review]

File: apps/directory/src/property-config/initialLandingpage.js (hunk 1 above)
Comment (esthervanenckevort) [reply apps/directory/src/property-config/initialLandingpage.js:66]: I think we should do it like Morris indicated, that is the more future proof way and if I look at the ticket is already indicates that the files are in the public/img/ directory, which is already being served.
e.g. https://directory.bbmri-eric.eu/public_html/apps/directory/img/bacteria.jpg works

**Review by esthervanenckevort — APPROVED** [review]
Double checked in browser and images are now served from the app.
