### PR TITLE
fix: 5773 fix clear ontology

### LINKED ISSUE #5773: Error on clear ontology input (  tree )
### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

13.73.4

### Description

Extension of #5715 => reference clearing is solved. However as indicated in the review #5716 it still does not work properly for all columnTypes:

Furthermore tested it with all available (working) types in type test schema, and the removal of the following columnTypes is also not saved properly:

- ontology type small (tree)
- ontology type large (tree) 

### Reproduction steps

1. Go to 'https://emx2.dev.molgenis.org' and sign in 
2. Click on 'type test' schema
3. Add a row by filling in the above mentioned columnTypes
4. Save the data
5. Clear all above filled in fields and save again
6. Close the form and either check in the table explorer or reopen the record
7. See that the data is still there

### Expected behaviour

When I delete data from a form that has already been saved, it should stay deleted also after re-saving the form again.

### System configuration

- Device: 
- Operating system: 
- Browser:

### System configuration

- Device: 
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by connoratrug**
### What are the main changes you did
- pass null instead of undefined to keep key in map ( empty value gets send to server)
- fix test warnings around missing plugin

Closes #5773

### How to test
see #5773 

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: apps/tailwind-components/app/components/input/Ontology.vue [hunk 1]
```diff
@@ -490,37 +493,21 @@ let lastSearchValue: string = "";
 let isSearching = false;
 
 watch(searchTerms, (newValue, oldValue) => {
-  console.log("🔍 Search watcher triggered:", {
```
Comment (mswertz) [inline apps/tailwind-components/app/components/input/Ontology.vue]: sorry, I though I had filtered this
