### PR TITLE
fix: results for removing search

### LINKED ISSUE #4857: bug(directory): removing search term leads to 'no biobanks were found'
### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

v11.71.2

### Description

When I search for something in the Directory and then clear away the search term, I get the result 'no biobanks were found'. 

### Reproduction steps

1. Go to https://directory.bbmri-eric.eu/ERIC/directory/#/catalogue
2. Type anything in the search bar, e.g. 'lines'
3. See matching search results
4. Delete search term from search bar
5. See no results displayed and 'no biobanks were found'

### Expected behaviour

I expect the homepage containing all biobanks to be displayed, as it was before searching. 

### System configuration

- Device: computer, MacOS Sequoia 15.3.2, Firefox v136.0.1

Has also been externally confirmed in Edge, Firefox, Chrome, Brave.

### PR DESCRIPTION
**Pull request by chinook25**
### What are the main changes you did
- fixes #4857 

### How to test
- see issue

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: apps/directory/src/stores/filtersStore.ts [hunk 1]
```diff
@@ -338,8 +338,12 @@ export const useFiltersStore = defineStore("filtersStore", () => {
     bookmarkTriggeredFilter.value = fromBookmark ?? false;
 
     if (typeof value === "string" || typeof value === "boolean") {
-      filters.value[filterName] = value;
-      checkoutStore.setSearchHistory(`${filterName} filtered on ${value}`);
+      if (value === "") {
+        delete filters.value[filterName];
```
Comment (esthervanenckevort) [inline apps/directory/src/stores/filtersStore.ts:342]: Shouldn't you update the search history to say that the filter was removed (like it is done for arrays)?

**Review by esthervanenckevort — APPROVED** [review]
Functionally it works. I did notice that the filter history is not updated when the filter is deleted.

File: apps/directory/src/stores/filtersStore.ts (hunk 1 above)
Comment (chinook25) [reply apps/directory/src/stores/filtersStore.ts:342]: Right you are! Added it.
