### PR TITLE
test: refactor to make test use set admin password. closes #435

### LINKED ISSUE #435: Building the software results in db changes
**What version of EMX2 are you using (see footer)**
8.x

**Describe the bug**
When i run the gradle build command the e2e tests get run these update the database ( reset admin pw)

**To Reproduce**
initialise app with given admin PW as described in the docs
(re)build the jar using gradle
run the app again 
login as admin using the given admin pw

**Expected behavior**
succesfull admin login using PW as set during initialisation

### PR DESCRIPTION
**Pull request by mswertz**
Motivation: running 'gradle test' will change your database. If you want to use test database then you must be able to use different admin name and admin password. 

Result: You can now set environment variables to use other database/password instead of hardcode "admin".

See installation manual how to set these passwords.

### CODE REVIEW

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java [hunk 1]
```diff
@@ -438,9 +443,31 @@ public Integer getDatabaseVersion() {
...
+  public String getAdminUserName() {
+    return ADMIN_USER;
+  }
+
+  @Override
+  public String getAdminPasswordDefault() {
+    return (String)
+        EnvironmentProperty.getParameter(
+            Constants.MOLGENIS_ADMIN_PW, ADMIN_PW_DEFAULT, STRING);
+  }
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java:462]: not sure about making this public, now any caller can access the env param.

File: docs/dev_quickstart.md [hunk 2]
```diff
@@ -97,19 +97,19 @@ Requires only [docker compose](https://docs.docker.com/compose/) and [yarn 1.x](
   ```
   Typically the app is then served at http://localhost:9090 (look at the console to see actual port number)
 
-## Tips
+## FAQ
```
Comment (connoratrug) [inline docs/dev_quickstart.md:100]: Personally prefer starting the title with the most important word, allows for quickly scanning the docs.

**Comment by mswertz** [comment]
[test: make test use own password. closes #435](https://trello.com/c/r6E3EWtS/229-test-make-test-use-own-password-closes-435)

File: docs/dev_quickstart.md (hunk 2 above)
Comment (mswertz) [reply docs/dev_quickstart.md:100]: what would you recommend here?

Comment (connoratrug) [reply docs/dev_quickstart.md:100]: Tips of FAQ ? , both are fine IMO , more a general note on starting labels/headers with a significant word ( instead of , How to ... , What ... , ).  ( nice tips at : https://material.io/design/communication/writing.html#principles , section "Write simply and directly"

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java (hunk 1 above)
Comment (mswertz) [reply backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java]: refactored.

File: docs/dev_quickstart.md [hunk 3]
```diff
@@ -122,16 +122,23 @@ fi
...
+### How to reset gradle cache/deamon
 
 Sometimes it help to reset gradle cache and stop the gradle daemon
 
 ```
 ./gradlew --stop rm -rf $HOME/.gradle/
 ```
 
-### Delete all schemas (destroys all your data!)
+### How to delete all schemas (destroys all your data!)
```
[the remark this answers is not in the document]
Comment (mswertz) [reply docs/dev_quickstart.md]: I have reverted this change

**Review by connoratrug — APPROVED** [review]
