### PR TITLE
fix: show labels for chapters

### LINKED ISSUE #2719: headings in Chapters are visible with columnName instead of Labels
**What version of EMX2 are you using (see footer)**
v8.210.3
**Describe the bug**
If there are headings in form, when in edit-mode, chapters are only shown with their columnName. In form itself headings are shown with label.

**To Reproduce**
1. Go to 'https://ithaca-emx2test.molgeniscloud.org/ILIAD/tables/#/Subject'
2. Create new subject
3. Forms opens, on right chapters are shown
4. See columnName instead of label

**Expected behavior**
I would like to see labels instead of columnName. This can also be a option to switch on or off. 

**Screenshots**

Scherm­afbeelding 2023-09-05 om 10 57 32

### PR DESCRIPTION
**Pull request by chinook25**
Fixes #2719
Use heading labels if they are available.

### CODE REVIEW

File: apps/molgenis-components/src/components/forms/EditModal.vue [hunk 1]
```diff
@@ -286,6 +286,16 @@ export default {
       this.rowErrors = getRowErrors(this.tableMetaData, this.rowData);
       this.saveDisabledMessage = getSaveDisabledMessage(this.rowErrors);
     },
+    getHeadingLabel(headingName: string) {
+      const column = this.tableMetaData.columns.find(
+        (column) => column.name === headingName
```
Comment (mswertz) [inline apps/molgenis-components/src/components/forms/EditModal.vue:291]: I know it is existing code, but can you think if we indeed want column.name here or column.identifier?

**Review by mswertz — APPROVED** [review]

File: apps/molgenis-components/src/components/forms/EditModal.vue (hunk 1 above)
Comment (chinook25) [reply apps/molgenis-components/src/components/forms/EditModal.vue:291]: I did, in #2715 it is changed to Id because the logic behind it gets a bit simplified.
