### PR TITLE
fix: when column name is 'count' there were conflicts on graphql _agg api

### LINKED ISSUE #922: ColumnType int throws subSelectionRequired error
**What version of EMX2 are you using (see footer)**
8.43.1

**Describe the bug**

Column that has the type `int` throws the following error.

```
Error: Validation error of type SubSelectionRequired: Sub selection required for type speciesAggregatorForcount of field count @ 'species_agg/count'
``` 

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. Click on '+' to create a new database
3. Import attached schema into the new database
4. Navigate to the table `species`
5. See error

**Expected behavior**
All data should be visible

**Desktop (please complete the following information):**
 - OS: macOS v10.15.7
 - Browser: Firefox
 - Version: 96.0.2
 
**Additional context**
None
[birddata_emx2.xlsx](https://github.com/molgenis/molgenis-emx2/files/7950499/birddata_emx2.xlsx)

### PR DESCRIPTION
**Pull request by mswertz**
problem was caused by the experimental 'max', 'min', 'sum', 'avg'.

Before this pull request the api structure was
- count
- columname/max
- columname/min
- etc
when the columname == 'count' this resulted in problems

Now the api structure is:
- count
- max/columnname
- min/columnname
- etc
Then this conflict is not possible.

Notes: 
- the even more experimental 'group by' has been disabled until we have time to do this properly
- took the opportunity to refactor to jooq jsonObject and jsonAgg functions (instead of doing that ourselves)

fixes #922

### CODE REVIEW

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestRefBack.java [hunk 1]
```diff
@@ -132,18 +132,18 @@ public void execute(ColumnType refArrayOrMref) {
     System.out.println(query.retrieveJSON());
 
     query = parts.agg(s("count"));
-    assertTrue(query.retrieveJSON().contains("\"count\": 5"));
+    assertTrue(query.retrieveJSON().contains("\"count\" : 5"));
```
Comment (mswertz) [inline backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestRefBack.java:135]: silly spaces, but couldn't see how to fix

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestSchemaUpdate.java [hunk 2]
```diff
@@ -16,12 +15,7 @@
   @BeforeClass
   public static void setUp() {
     db = TestDatabaseFactory.getTestDatabase();
-    db.createSchema(TestSchemaUpdate.class.getName(), desc);
-  }
-
-  @AfterClass
-  public static void tearDown() {
-    db.dropSchema(TestSchemaUpdate.class.getName());
+    db.dropCreateSchema(TestSchemaUpdate.class.getName(), desc);
```
Comment (mswertz) [inline backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestSchemaUpdate.java:18]: this gave now and then an issue that schema was already created.
