### PR TITLE
fix: don't count invisible fields towards errors

### LINKED ISSUE #2752: Invisible required field prevent saving row
**What version of EMX2 are you using (see footer)**
v8.218.0

**Describe the bug**
In the row edit form, when there is a field that is both invisible (due to expressions) and required, it still counts as an error, preventing saving

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Create a Heading with a hidden field after it
3. Add a row, filling out the required fields that are currently visible.
4. See that the header you made is hidden due to it having no fields, 
5. See that the error count is still 1 while no erroneous chapters are in the sidebar. 

**Expected behavior**
Empty required fields that are currently invisible are not counted towards the number of errors in a form. 

**Note**
Making the required field visible and filling it removes the error (as aspected it would, given this bug).

### PR DESCRIPTION
**Pull request by chinook25**
Fixes #2752

### CODE REVIEW

File: apps/molgenis-components/src/components/forms/formUtils/formUtils.ts [hunk 1]
```diff
@@ -28,6 +28,10 @@ function getColumnError(
   // FIXME: longs are not checked
   const missesValue = value === undefined || value === null || value === "";
 
+  if (!isColumnVisible(column, values, tableMetaData)) {
```
Comment (mswertz) [inline apps/molgenis-components/src/components/forms/formUtils/formUtils.ts:31]: should this code be at line 24? Because now we still run isInvalidNumber?

File: apps/molgenis-components/src/components/forms/RowEdit.vue [hunk 2]
```diff
@@ -110,7 +110,7 @@ export default {
       default: () => ({}),
     },
   },
-  emits: ["update:modelValue", "errorsInForm"],
```
Comment (mswertz) [inline apps/molgenis-components/src/components/forms/RowEdit.vue:113]: we don't need this anymore?

**Review by mswertz — APPROVED** [review]

File: apps/molgenis-components/src/components/forms/RowEdit.vue (hunk 2 above)
Comment (chinook25) [reply apps/molgenis-components/src/components/forms/RowEdit.vue:113]: Nope, I moved that functionality to the outer component in an earlier PR, but forgot to remove the emits here.

File: apps/molgenis-components/src/components/forms/formUtils/formUtils.ts (hunk 1 above)
Comment (chinook25) [reply apps/molgenis-components/src/components/forms/formUtils/formUtils.ts:31]: Doesn't really matter, since isInvalidNumber does not cause a return yet. This way is a bit more expensive, but I think it is more readable this way  (first declaring al vars, then doing al the actual return logic)
