### PR TITLE
fix(catalogue): display other organisation name in case of no ROR

### LINKED ISSUE #5659: In catalogue app when Organisations.organisation is not filled out, organisation name needs to be taken from Organisation.other organisation
# Note

Can this be done via if then in the label field? ie.${organisation.organisation?.name || organisation.otherOrganisation}

### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

Software version: v13.67.0

### Description

Since catalogue data model version 7.x we select organisations from the ROR  When an organisation is not listed in our subset of the ROR: https://ror.org/. We have our own subset of organisations that can be chosen from in the CatalogueOntologies: https://github.com/molgenis/molgenis-emx2/blob/master/data/_ontologies/Organisations.csv. 

In the UI, some fields from that ontology are used. However, sometimes people cnnot find their organisation listed and they are instructed to fill out 'other organisation' in that case. For the UI, we need to refer to 'other organisation'  when the field Organisations.organisation is not filled out

### Reproduction steps

1. Go to 'https://emx2.dev.molgenis.org'
2. log in and upload this csv to catalogue-demo schema:   

[Organisations.csv](https://github.com/user-attachments/files/24130244/Organisations.csv)

  (demo data will be incorporated, but still in PR: https://github.com/molgenis/molgenis-emx2/pull/5660) 
3. Go to https://catalogue.dev.molgenis.org/testNetwork1/collections/testCohort2
4. Scroll down to Organisations
6. See that one of the organisations has no name displayed

### Expected behaviour

When the field Organisations.organisation is not filled out, organisation name needs to be taken from the field 'Organisation.other organisation'

### System configuration

- Device: 
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by chinook25**
### What are the main changes you did
- fixes #5659 

### How to test
- see issue
- https://preview-catalogue-pr-5787.dev.molgenis.org/testNetwork1/collections/testCohort2

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/shacl/ShaclSelectorTest.java [hunk 1]
```diff
@@ -63,8 +63,7 @@ void testFilteredShaclSet() {
   @Test
   void testAllNamesPresentInFiltered() {
     // does not test full file but only names for simplicity (1 shacl set is tested fully)
-    Set<String> expected =
-        Set.of("fdp-v1.2", "dcat-ap-v3", "hri-v2.0.2", "ejp-rd-vp");
+    Set<String> expected = Set.of("fdp-v1.2", "dcat-ap-v3", "hri-v2.0.2", "ejp-rd-vp");
```
Comment (chinook25) [inline backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/shacl/ShaclSelectorTest.java]: everytime I run gradle this changes, so I'm just commiting it now.

**Review by hslh — APPROVED** [review]
Does what it needs to do, displays organisation information from ROR when filled in, name from 'other organisation' when not filled in.
