### PR TITLE
fix: issue that roles are shared between schema with equals names if uppercased.

### LINKED ISSUE #405: 'testCohort' and 'testcohort' share user authorization
**What version of EMX2 are you using (see footer)**
7.4.1

**Describe the bug**
When two schemas have identical names but different capitalization, their user permissions are shared.

**To Reproduce**
1. Go to 'https://data-catalogue-staging.molgeniscloud.org/'
2. Click on 'testcohort'
3. Add a user via settings
4. See user back in 'testCohort' settings
5. Try to delete either one of the databases, get error message.

**Expected behavior**
I expect user permissions to be separated for separate schemas. I expect to be able to delete either one of the databases.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mswertz**
fix: schema roles should be case sensitive to prevent permissions to be shared between schema with equal uppercase names. closes #405

To reproduce problem:

1. in PREVIOUS version create two schemas with same name, e.g. add 'Pet store' next to existing 'pet store'

2. see the problem that 'Pet store' has same members as 'pet store' while you didn't create it

Added migration. To test if that works

3. check, and see roles with "MG_ROLE_PET STORE" having uppercase while schema is "pet store"
using 'psql -u molgenis' and then 'SELECT rolname FROM pg_roles;'

4. run THIS version, which should then run the migration
gradle run

5. check, and see roles with "MG_ROLE_pet store" having same case as schema names
using 'psql -u molgenis' and then 'SELECT rolname FROM pg_roles;'

### CODE REVIEW

**Comment by mswertz** [comment]
I gave this a thought and I think we could create a migration.

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java [hunk 1]
```diff
@@ -195,4 +196,19 @@ public void testRole() {
       database.clearActiveUser();
     }
   }
+
+  @Test
+  public void testCaseSensitiveSchemaNames() {
+    // following bug
+    Schema s1 = database.dropCreateSchema("testCaseSensitiveSchemaNames");
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java:203]: what is dropCreateSchema :S  ? has to read the impl to find out  , suggest recreateSchema

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java [hunk 2]
```diff
@@ -195,4 +196,19 @@ public void testRole() {
       database.clearActiveUser();
     }
   }
+
+  @Test
+  public void testCaseSensitiveSchemaNames() {
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java:201]: Suggest having use tests for create, drop, .... and then adding assertion for case sensitive .  A integration test can then check is UserA can create , add .. some find ScHeMaA and not in schemaA

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/MetadataUtils.java [hunk 3]
```diff
@@ -144,7 +144,7 @@ protected static void init(DSLContext j) {
                   "DROP POLICY IF EXISTS {0} ON {1}",
                   name(SCHEMA_METADATA.getName() + "_POLICY"), SCHEMA_METADATA);
               jooq.execute(
-                  "CREATE POLICY {0} ON {1} USING (pg_has_role(CONCAT({2},UPPER({3}),'/Viewer'),'MEMBER'))",
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/MetadataUtils.java:147]: add note to PR that explains before pr schema name was case insensitive and converted to uppercase and now after pr is case sensitive. And suggest a way for users/admins to 'fix' there deployments ( is there a way to fix things without having admin access to the pg dm ? ) .

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchemaMetadataExecutor.java [hunk 4]
```diff
@@ -124,14 +124,14 @@ private static void updateMembershipForUser(
   }
 
   static String getRolePrefix(String name) {
-    return Constants.MG_ROLE_PREFIX + name.toUpperCase() + "/";
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchemaMetadataExecutor.java:127]: same for roles , PR should not only clearly indicate that this change is breaking of should include details on what breaks and how it can be 'fixed'

**Review by connoratrug — COMMENTED** [review]
code changes seem oke , but i get a bit worried about only a single test that gets added. I would have expected several units test to fail because of the change.  The fact that no tests need to be updated suggests that is req was not under test. the problem imo is that the business logic is expressed in sql and not in (java)code, and therefore does not get picked up by code cov. would suggest adding unit tests to assert the details of the database operations as these are hard to debug en expensive to fix ( breaking change leads to lost of work for operations).

This breaking change also suggest to me we should look into adding a migration system asap

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java (hunk 1 above)
Comment (mswertz) [reply backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java:203]: would dropAndCreateSchema work for you as well? Would stay closer to psql nomenclature

Comment (connoratrug) [reply backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java:203]: had to look up 'nomenclature' :D , but sure its a bit more clear to me, personally i would prefer having a create and a drop function with a optional dropIfExist param ( or a fail if does not exist  ) but dropAndCreateSchema does indicate what is going on

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/MetadataUtils.java (hunk 3 above)
Comment (mswertz) [reply backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/MetadataUtils.java:147]: Minimally, we would then need to rename the roles. Would be something like query below:
`
do
$$
DECLARE temprow RECORD;
DECLARE nm VARCHAR;
BEGIN 
	FOREACH nm in array array['Viewer','Manager','Owner','Editor'] LOOP
		BEGIN
			FOR temprow IN select distinct r.rolname as oldname, 'MG_ROLE_'||s.table_schema||'/'||nm as newname FROM pg_catalog.pg_roles r join "MOLGENIS"."schema_metadata" s ON(r.rolname ILIKE 'MG_ROLE_'||s.table_schema||'/'||nm||'%') 
			LOOP
				IF NOT EXISTS(SELECT FROM pg_catalog.pg_roles WHERE rolname = temprow.newname) THEN
					RAISE NOTICE 'Value: %', temprow.oldname || ' newname ' ||temprow.newname;
					EXECUTE 'ALTER ROLE "'||temprow.oldname||'" RENAME TO "'||temprow.newname||'"';
				END IF;
			END LOOP;
		END;
	END LOOP;
END;
$$
`

In addition we must then update any RLS policies that have been created that use these. Might be more tricky

**Comment by mswertz** [comment]
> code changes seem oke , but i get a bit worried about only a single test that gets added. I would have expected several units test to fail because of the change. The fact that no tests need to be updated suggests that is req was not under test. the problem imo is that the business logic is expressed in sql and not in (java)code, and therefore does not get picked up by code cov. would suggest adding unit tests to assert the details of the database operations as these are hard to debug en expensive to fix ( breaking change leads to lost of work for operations).
> 
> This breaking change also suggest to me we should look into adding a migration system asap

This is all 'under the hood' so it should imo not lead to many failing tests. Reason is users need to do something kinda stupid to see this issue: create schemas with same names but only different casing. Normal users would not do this to prevent confusion except by accident (which is how we found out). This is even so unwise that I considered to make schema names case-insensitive (which is actually source of this bug, initially it was) but that is probably to much restricting our users. I don't agree with your logic about coverage as being a reason for putting business logic in java instead of sql. However, agree with your point to add specific a test that now fail on case sensitivity in the right places.

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java (hunk 2 above)
Comment (mswertz) [reply backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java:200]: tests added

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java (hunk 1 above)
Comment (mswertz) [reply backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java:202]: with that param is a more expensive refactor :-). Happy to rename though. Could also make it createOrReplaceIfExists() if you like that better

Comment (connoratrug) [reply backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java:202]: leave it up to you to decide, not a blocking issue , just some thing i had to look up

**Comment by mswertz** [comment]
We are implementing migrations; wait merge so we can make this a non-braking change.

**Comment by mswertz** [comment]
[fix: issue that roles are shared between schema with equals names if uppercased.](https://trello.com/c/griZ0s2F/203-fix-issue-that-roles-are-shared-between-schema-with-equals-names-if-uppercased)

File: build.gradle [hunk 5]
```diff
@@ -132,3 +132,10 @@ jar {
     }
 }
 
+task cleandb(type:JavaExec) {
+    group = "Execution"
+    description = "Clean database. Carefull, will delete all MOLGENIS stuff"
+    classpath = sourceSets.main.runtimeClasspath
+    main = "org.molgenis.emx2.AToolToCleanDatabase"
+}
+
```
Comment (connoratrug) [inline build.gradle:141]: mention existence, how to use and what it does to dev docs

File: backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration2.sql [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+         join "MOLGENIS"."schema_metadata" s ON (r.rolname ILIKE 'MG_ROLE_'||s.table_schema||'/'||nm||'%') LOOP
+				IF NOT EXISTS(SELECT FROM pg_catalog.pg_roles WHERE rolname = temprow.newname) THEN
+					RAISE NOTICE 'Value: %', temprow.oldname || ' newname ' ||temprow.newname;
+EXECUTE 'ALTER ROLE "' || temprow.oldname || '" RENAME TO "' || temprow.newname || '"';
+END IF;
+END LOOP;
+END;
+END LOOP;
+-- alter RLS policy
+ALTER POLICY "schema_metadata_POLICY" ON "MOLGENIS"."schema_metadata" USING (pg_has_role((concat('MG_ROLE_', table_schema, '/Viewer'))::name, 'MEMBER'::text));
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration2.sql:24]: add test

**Review by connoratrug — COMMENTED** [review]
- add test for migration(s)
- add note tool and how to run in dev docs

File: build.gradle (hunk 5 above)
Comment (mswertz) [reply build.gradle:141]: will add to both dev and ops docs

File: backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration2.sql (hunk 6 above)
Comment (mswertz) [reply backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration2.sql:24]: done

**Comment by mswertz** [comment]
> * add test for migration(s)
> * add note tool and how to run in dev docs

done

**Review by connoratrug — APPROVED** [review]
