### PR TITLE
fix: scrollbar should be shown for large modal screens

### LINKED ISSUE #934: Scroll bar in forms is missing
**What version of EMX2 are you using (see footer)**
8.43.3

**Describe the bug**
The scroll bar in forms is missing. You cannot move throughout the form anymore.

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/catalogue/tables/#/'
2. Open a table, try to edit, see that the scroll bar is missing.

### PR DESCRIPTION
**Pull request by mswertz**
Closes #934

### CODE REVIEW

**Comment by BrendaHijmans** [comment]
refback tables are not scaling well in forms

**Comment by erikzwart** [comment]
PR-937_form-header-overflow

**Comment by mswertz** [comment]
> refback tables are not scaling well in forms

was this a new issue? anyway, added fix for that too

File: apps/styleguide/src/layout/LayoutModal.vue [hunk 1]
```diff
@@ -4,7 +4,7 @@
       v-if="show"
       class="modal fade show"
       role="dialog"
-      style="display: block"
+      style="display: block; overflow: scroll"
```
Comment (connoratrug) [inline apps/styleguide/src/layout/LayoutModal.vue:7]: why use style instead of style tag and css, and why would this style be needed , what introduced this bug ? , just add more style weight might hide the underlying issue

**Review by erikzwart — APPROVED** [review]
Issue with overflow is fixed for this screen

PR-937_form-header-overflow-fix
