### PR TITLE
fix(forms): refLink and refModal failed on composite keys due to expandLevel > 1. closes #4002

### LINKED ISSUE #4002: Ref columns with composite keys are broken in forms
**What version of EMX2 are you using (see footer)**
v10.93.1

**Describe the bug**
When trying to add a new entry in a table that references another table on the same schema, the entries in that that table cannot be loaded and the message `Failed to load data` is shown (see screenshot 1).
When a referenced value in an existing entry is clicked, a dialog pops up. Instead of showing the information related to the referenced item, a spinner is shown spinning ad infinitum (see screenshot 2).
A quick look into the GraphQL queries reveals that the referenced table is requested with a filter that contains too much information.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Sign in as admin
3. Go to the 'catalogue' schema, to the tables view
4. Click the 'Variables' table and click on the ➕ to add a new entry.
5. Select any 'resource' in the first field and then click the 'dataset' field
6. See error 1
7. Close the entry dialog and click on any cell in the 'dataset' column
8. See error 2

**Expected behavior**
The data should just load and appear.

**Screenshots**
Screenshot 1
image
Screenshot 2
image

**Additional context**
The 'Resources' table referenced in the column 'resource' does load, however.

### PR DESCRIPTION
**Pull request by mswertz**
closes #4002 

changes:
- make sure refSchema is always returned from server (even if same as parent)
- apply convertRowToPrimaryKey before using refLink value as ref filter 
- reset reflinked column if the reflink changes instead of error checking

N.B. why are there two convertRowToPrimaryKey  implementations?

### CODE REVIEW

**Comment by chinook25** [comment]
> N.B. why are there two convertRowToPrimaryKey implementations?

Iirc Connor moved it to the client, but in there it uses the cached current schema. There are a few cases where the key of another schema is needed, hence the old version still kicks around (which retrieves the metadata of the schemaId). I think due to changes in the client, the one in util.ts has become obsolete and can be replaced.

File: apps/molgenis-components/src/components/forms/formUtils/formUtils.ts [hunk 1]
```diff
@@ -206,31 +203,6 @@ export function executeExpression(
   return func(simplePostClient, ...Object.values(copy));
 }
 
-function isRefLinkWithoutOverlap(column: IColumn, values: Record<string, any>) {
-  if (!column.refLinkId) {
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/formUtils/formUtils.ts:210]: Don't forget to also remove the unittest

File: apps/molgenis-components/src/components/forms/RowEdit.vue [hunk 2]
```diff
@@ -163,40 +165,49 @@ export default {
...
+    //update reflink filters and reset values if reflink changes
+    async updateRefLinks(changedColumn: IColumn) {
+      //need to figure out what refs overlap with the changed column
+      for (const column1 of this.tableMetaData.columns) {
+        if (
+          this.internalValues[changedColumn.id] &&
+          column1.refLinkId == changedColumn.id &&
+          this.showColumn(column1)
+        ) {
+          console.log("check");
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/RowEdit.vue:177]: debug line

File: apps/molgenis-components/src/components/forms/RowEdit.vue [hunk 3]
```diff
@@ -163,40 +165,49 @@ export default {
...
+              for (const column2 of table.columns) {
+                if (
+                  column2.key === 1 &&
+                  column2.refTableId === changedColumn.refTableId
+                ) {
+                  //reset the value and the filter
+                  this.internalValues[column1.id] = null;
+                  //and then define new filter setting
+                  this.refFilter[column1.id] = {};
+                  this.refFilter[column1.id] = {
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/RowEdit.vue:191]: this double assignment seems unnecessary

File: apps/molgenis-components/src/components/forms/RowEdit.vue [hunk 4]
```diff
@@ -163,40 +165,49 @@ export default {
...
-                    column3.refTableId === column2.refTableId
-                  ) {
-                    filter[column3.id] = {
+    //update reflink filters and reset values if reflink changes
+    async updateRefLinks(changedColumn: IColumn) {
+      //need to figure out what refs overlap with the changed column
+      for (const column1 of this.tableMetaData.columns) {
+        if (
+          this.internalValues[changedColumn.id] &&
+          column1.refLinkId == changedColumn.id &&
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/RowEdit.vue:174]: ===

File: apps/molgenis-components/src/components/forms/RowEdit.vue [hunk 5]
```diff
@@ -163,40 +165,49 @@ export default {
...
-                table.columns.forEach((column3) => {
-                  if (
-                    column3.key === 1 &&
-                    column3.refTableId === column2.refTableId
-                  ) {
-                    filter[column3.id] = {
+    //update reflink filters and reset values if reflink changes
+    async updateRefLinks(changedColumn: IColumn) {
+      //need to figure out what refs overlap with the changed column
+      for (const column1 of this.tableMetaData.columns) {
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/RowEdit.vue:171]: A bit more contextual name would be nice here, instead of `column1`.

File: apps/molgenis-components/src/components/forms/RowEdit.vue [hunk 6]
```diff
@@ -163,40 +165,49 @@ export default {
...
+          this.internalValues[changedColumn.id] &&
+          column1.refLinkId == changedColumn.id &&
+          this.showColumn(column1)
+        ) {
+          console.log("check");
+          //check how the refTableId overlaps with columns in our column
+          for (const table of this.schemaMetaData.tables) {
+            if (table.id === column1.refTableId) {
+              console.log("check2");
+              for (const column2 of table.columns) {
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/RowEdit.vue:182]: same as with column1, maybe in the spirit of `refTableColumn`.

File: apps/molgenis-components/src/components/forms/RowEdit.vue [hunk 7]
```diff
@@ -163,40 +165,49 @@ export default {
...
+                if (
+                  column2.key === 1 &&
+                  column2.refTableId === changedColumn.refTableId
+                ) {
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/RowEdit.vue:186]: Since we are only interested in primary keys, wouldn't a find be more appropriate here to use a find instead of a for-loop?

Comment (chinook25) [reply apps/molgenis-components/src/components/forms/RowEdit.vue:186]: It would be be good to split out this loop and build a record with all the relevant keys and then combine that with column1, so we don't loop over the schemaMetadata several times. This would also reduce the complexity of the function a bit (it's kinda hard to read with so much nesting).

**Review by chinook25 — CHANGES_REQUESTED** [review]
Fixes the first error of the issue, however the second one still exists. Will that be a separate PR? 
Further more, some algorithmical and some minor comments.

File: apps/molgenis-components/src/components/forms/formUtils/formUtils.ts (hunk 1 above)
Comment (mswertz) [reply apps/molgenis-components/src/components/forms/formUtils/formUtils.ts:210]: thx

**Comment by mswertz** [comment]
> Fixes the first error of the issue, however the second one still exists. Will that be a separate PR? Further more, some algorithmical and some minor comments.

Indeed, missed that there is a second issue. Will take a look if it is related or not. Otherwise split a new issue to be fixed in next PR

File: apps/molgenis-components/src/components/forms/RowEdit.vue (hunk 3 above)
Comment (mswertz) [reply apps/molgenis-components/src/components/forms/RowEdit.vue:191]: ah yeah, legacy from earlier try

File: apps/molgenis-components/src/components/forms/RowEdit.vue (hunk 5 above)
Comment (mswertz) [reply apps/molgenis-components/src/components/forms/RowEdit.vue:171]: you are right. Will rewrite so I can use more meaningful names

File: apps/molgenis-components/src/components/forms/RowEdit.vue (hunk 6 above)
Comment (mswertz) [reply apps/molgenis-components/src/components/forms/RowEdit.vue:182]: ditto

File: apps/molgenis-components/src/components/forms/RowEdit.vue (hunk 7 above)
Comment (mswertz) [reply apps/molgenis-components/src/components/forms/RowEdit.vue:186]: that is a good idea. That would make it much more readible

Comment (mswertz) [reply apps/molgenis-components/src/components/forms/RowEdit.vue]: done

File: apps/molgenis-components/src/components/forms/RowEdit.vue [hunk 8]
```diff
@@ -1,5 +1,6 @@
 <template>
   <div>
+    {{ refFilter }}
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/RowEdit.vue]: debug line?

File: apps/molgenis-components/src/components/forms/RowEdit.vue [hunk 9]
```diff
@@ -163,40 +166,41 @@ export default {
...
+          (col: IColumn) =>
+            col.key === 1 && col.refTableId === changedColumn.refTableId
+        );
+        for (const overlappingKey of overlappingRefColumns) {
+          //reset the value and the filter
+          this.internalValues[refLinkColumn.id] = null;
+          //and then define new filter setting
+          this.refFilter[refLinkColumn.id] = {
+            [overlappingKey.id]: {
+              //@ts-ignore
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/RowEdit.vue]: ts-ignore is not needed

**Review by chinook25 — APPROVED** [review]
