### PR TITLE
fix: download per table csv/excel/rdf when having spaces in names. closes #2987 closes #2966. closes #2902

### LINKED ISSUE #2902: Sometimes I can't download files in the tables view
**What version of EMX2 are you using (see footer)**
[v8.213.29](https://github.com/molgenis/molgenis-emx2/releases/tag/vv8.213.29)

**Describe the bug**
Sometimes I can't download files in the tables view. But I tried multiple staging areas and in some I still can. My guess would be when there are relatively many rows in the table. For example, testCohort works fine, but ELSPAC and ALSPAC give errors.
(Even weirder: I don't get an error for the ATHLETE variables table, but an external datamanager does.)

**To Reproduce**
1. Go to 'https://data-catalogue.molgeniscloud.org/ELSPAC/tables/#/VariableMappings'
2. Click on 'download'
3. Download all rows (file type doesn't matter)
4. See error:
```
{
  "errors" : [
    {
      "message" : "Table VariableMappings unknown"
    }
  ]
}
```

### LINKED ISSUE #2966: Cannot download catalogue tables with old camelCase names from table view
**What version of EMX2 are you using (see footer)**
vxx.yy.zz

**Describe the bug**

**To Reproduce**
1. Go to e.g. https://emx2.dev.molgenis.org/catalogue-demo/tables/#/DataSources or https://emx2.dev.molgenis.org/catalogue-demo/tables/#/CollectionEvents
2. Click on download as csv or Excel
3. See error: 
{
  "errors" : [
    {
      "message" : "Table DataSources unknown"
    }
  ]
}

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #2987: Download all links don't work in case of a table name with a space
**What version of EMX2 are you using (see footer)**
v10.0.8

**Describe the bug**
If I click on the Download all rows in the table explorer I get an error that the table is not found if the table name contains spaces.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. Click on 'Catalogue-demo'
3. Click on 'Tables'
4. Click on 'Collection Events'
5. Click on 'Download'
6. Click on 'All rows' (for any of the options)'

**Expected behavior**
The data is downloaded.

**Actual Result**
I get the following error.
```
{
  "errors": [
    {
      "message": "Table CollectionEvents unknown"
    }
  ]
}
```
**Additional context**
The URLs use the table identifier, e.g. https://emx2.dev.molgenis.org/catalogue-demo/api/zip/CollectionEvents instead of the table name (in this example 'Collection Events').

### PR DESCRIPTION
**Pull request by mswertz**
closes #2987
 closes #2966
closes #2902

N.B. also depends on #3023 because might now also list tables not in current schema

### CODE REVIEW

**Review by esthervanenckevort — COMMENTED** [review]
I already added a fix for this to PR #3007. In principle this fix is also fine. I changed the code in the WebService and also deduplicated code there. Either fix is fine with me.

**Review by esthervanenckevort — APPROVED** [review]

**Review by esthervanenckevort — CHANGES_REQUESTED** [review]
Should actually merge the two getTableById functions, like I did in my PR and add a test.

**Review by esthervanenckevort — APPROVED** [review]

File: apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue [hunk 1]
```diff
@@ -6,19 +6,20 @@ definePageMeta({
   middleware: [
     function (to, from) {
       const config = useRuntimeConfig();
-      if(config.public.cohortOnly === true)
-      {
+      if (config.public.cohortOnly === true) {
```
Comment (mswertz) [inline apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue:9]: unrelated formatting, sorry
