### PR TITLE
fix: Order fetchOntologyOptions by order

### LINKED ISSUE #2831: ontologies order column is not the order in which lists are displayed in forms
**What version of EMX2 are you using (see footer)**
v8.223.0

**Describe the bug**
The order column in the ontology tables is not used to order the terms when they are presented in forms. 

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/CatalogueOntologies/tables/#/Countries?_order=ASC&_orderBy=order and see that Countries are ordered in a specific manner using the 'order' column. 
[image](https://github.com/molgenis/molgenis-emx2/assets/42644481/b7a9597e-2d4f-4d23-9541-60bbb9a10125)
2. Go to https://emx2.dev.molgenis.org/catalogue-demo/catalogue/#/cohorts, click on edit next to a cohort and move to population section
3. See the order in the countries column: 
image

**Expected behavior**
Order the presented list for an ontology in forms using the order column. This may give issues in tree-like ontologies. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #2831

What are the main changes you did:
- added sort by ( order ) option to ontology options fetch in client 

how to test:
- see issue details

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: apps/molgenis-components/src/client/client.ts [hunk 1]
```diff
@@ -307,6 +307,7 @@ const fetchOntologyOptions = async (
   const tableDataQuery = `query ${tableId} {
         ${tableId}(
           limit:100000
+          orderby: { name: ASC }
```
Comment (mswertz) [inline apps/molgenis-components/src/client/client.ts:310]: I thought the issue is that data managers can set the 'order' column and that that should be used? Or is now decided that alphabetical order is what is desired?

**Review by mswertz — COMMENTED** [review]
I think this is not addressing the expected behavior but it is also not bad. The expected behavior is `orderby: {order: ASC}` however order is hardly ever provided and then it should be ordered by what? name? I suppose it is now by insertion order?

**Review by chinook25 — APPROVED** [review]
