### PR TITLE
fix: session null error. closes #308

### LINKED ISSUE #308: App breaks when user has stale session
**What version of EMX2 are you using (see footer)**
6.5.9

**Describe the bug**
```
internal server error Error: Cannot invoke "String.equals(Object)" because the return value of "org.molgenis.emx2.web.MolgenisSession.getSessionUser()" is null: {"response":{"errors":[{"message":"Cannot invoke \"String.equals(Object)\" because the return value of \"org.molgenis.emx2.web.MolgenisSession.getSessionUser()\" is null"}],"status":400},"request":{"query":"{_session{email,roles},_settings{key,value},_manifest{ImplementationVersion,SpecificationVersion,DatabaseVersion}}"}}
```

**To Reproduce**
1. Use the app 
2. leave the tab open fore some time 
3. go back to using the app 

**Expected behavior**
No error , time out msg if appropriate

**Screenshots**
Screenshot 2021-06-23 at 13 22 35
 

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Additional context**
removing the cookies resolves the issue

### PR DESCRIPTION
**Pull request by mswertz**

### CODE REVIEW

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 1]
```diff
@@ -79,7 +79,8 @@ void updateSession(Request request, Response response) {
     }
 
     // check if session state and session user map still in sync
-    if (!session.getSessionUser().equals(session.getDatabase().getActiveUser())) {
+    if (session.getSessionUser() != null
+        && !session.getSessionUser().equals(session.getDatabase().getActiveUser())) {
```
Comment (connoratrug) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:83]: Lots of if-else-ing going on here combined with lots of null checking and fall-though cases, could really use unit tests that covers the different cases and describes each case

**Review by connoratrug — APPROVED** [review]
approve for note code needs TLC, suggestion was made to combine this with OpenID Connect integration
