### PR TITLE
fix: make computed fields front-end rendered

### LINKED ISSUE #3772: Computed Expression Values Not Shown in Table View When Accessed via Form with Refback in Edit Mode
**What version of EMX2 are you using (see footer)**
Software version: [v10.67.4](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.67.4).

**Describe the bug**
Users typically enter data through a form, which includes a reference back to additional information in another form. In my case, subject linked to subregistry "neuronet". The computed expressions in the extra information form, is not shown, when you open the extra information neuronet form via subject, the computed expression is not shown. The value from this computed expression is needed to set conditional requirement. The computede expression I use looks like this: "belongsToSubject?.subRegistry?.name".

**To Reproduce**
1. Use added datamodel to this issue
2. Create two databases "ontology" and "test"
3. The "test" database uses template "ERN_DASHBOARD" (no example data, needed)
4. The upload molgenis.csv to "test" database (will also create table names in ontology database)
5. Then go to "ontology" database and upload all data from zip (ontology1715852933712.zip)
6. Go back to "test" database and upload zip (dashboard_data.zip)
7. Create new subject in subject table.
8. Choose "NS Euronet ", with question "Patient belongs to specific subregistry"
9. Then save subject.
10. Edit patient, and add subregistry information, by clicking plus at "Link to extra information of NS Euronet extended RASopathy"
11. Add information (you already see first question "Belongs To Subregistry" NOT filled.
12. Save neuronet information
13. See error "Belongs To Subregistry" is empty

1. When you go to neuronet table
2. Edit created neuronet entry
3. And see that "Belongs To Subregistry" is filled with correct computed value

**Expected behavior**
Computed expression values should be displayed correctly in the table view, regardless of whether the form is accessed directly or through the main form with a refback.

**Screenshots**
neuronet-form opened from subject:
Scherm­afbeelding 2024-05-22 om 11 14 37
neuronet-form opened from neuronet table:
Scherm­afbeelding 2024-05-22 om 11 16 37

**Additional context**

- Users primarily enter data through the subject form, which references the extra information form via a refback.

- The computed expressions are essential for conditional required fields in the extra information form.
[dashboard_data.zip](https://github.com/molgenis/molgenis-emx2/files/15401045/dashboard_data.zip)
[ontology1715852933712.zip](https://github.com/molgenis/molgenis-emx2/files/15401046/ontology1715852933712.zip)
[molgenis.csv](https://github.com/molgenis/molgenis-emx2/files/15401047/molgenis.csv)

### PR DESCRIPTION
**Pull request by chinook25**
What are the main changes you did:
- fixes #3772 
- Also added error handling when computed have an error / can not be calculated. If a computed expression fails it will display `error: could not compute value` and also log the actual error in the console.

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: apps/molgenis-components/src/components/utils.ts [hunk 1]
```diff
@@ -200,3 +200,22 @@ export function deepEqual(
 function isObject(object: Record<string, any> | null): object is Object {
   return object !== null && typeof object === "object";
 }
+
+export function applyComputed(rows: IRow[], tableMetadata: ITableMetaData) {
+  return rows.map((row) => {
+    return tableMetadata.columns.reduce((accum: IRow, column: IColumn) => {
+      if (column.computed && column.columnType !== AUTO_ID) {
+        accum[column.id] = executeExpression(
```
Comment (mswertz) [inline apps/molgenis-components/src/components/utils.ts:208]: does this throw an exception if failing? I think not because I broke it ;-)

**Review by mswertz — CHANGES_REQUESTED** [review]
please add error handling such that erreoneous script doesn't break the screen.

how to test: create an invalid script and see that table explorer still works.

**Review by mswertz — APPROVED** [review]
