### PR TITLE
fix: added default mimetype when downloading files

### LINKED ISSUE #4833: Invalid Download Links for Non-Image Files Uploaded via UI or py-client
### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

Software version: v11.72.2-SNAPSHOT. Database version: 24.

### Description

When uploading non-image files (e.g., .owl, .obo) using the Up/Download UI or `py-client`, the generated download links do not work. The issue does not occur when uploading files manually.

**Observed Behavior**
The download link returns an error, stating that the page is unavailable or moved. Example error message:
`https://emx2.dev.molgenis.org/fileUpload/api/file/Versions/sourceFile/7ae40c758beb43ceb3e64424f415e5c4 werkt even niet, of de pagina kan verhuisd zijn naar een nieuw webadres.`

However, when using Up/Download UI, the files can be downloaded in ZIP format, confirming that they are successfully uploaded to the server.

### Reproduction steps

1. Create database and upload schema
[molgenis.csv](https://github.com/user-attachments/files/19281661/molgenis.csv)

2. Upload a records with files (testFile.zip)using Up/Download UI or `py-client`.

[testFile.zip](https://github.com/user-attachments/files/19281694/testFile.zip)

3. Navigate to Data Explorer and find the uploaded records.
4. Click on the file link with owl extension.
5. The link results in an error: 
```Deze site is niet bereikbaar
https://emx2.dev.molgenis.org/py_UploadTest/api/file/Versions/sourceFile/988aa63e444a4f0681533070e3f2c79d werkt even niet, of de pagina kan verhuisd zijn naar een nieuw webadres.
ERR_INVALID_RESPONSE
```
6. However, if you download the file using the "zip" option, the file downloads correctly.
7. Click on the file link with png extension and see that iamge is downloaded.

### Expected behaviour
The download link should allow direct access to the uploaded file, just as it does when the file is uploaded manually and like the png files

### System configuration
Upload Methods Tested:
✅ Manual Upload → Works
❌ Up/Download UI → Fails
❌ py-client → Fails

_No response_

### PR DESCRIPTION
**Pull request by harmbrugge**
Fixes #4833 where files with certain extensions cannot be download

### What are the main changes you did
- Added default mimetype for files downloaded via file api

### How to test
See issue [4833](https://github.com/molgenis/molgenis-emx2/issues/4833)

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Review by Fernananas — APPROVED** [review]
The issue with invalid download links for non-image files uploaded via the UI or Python client has been resolved. I tested file uploads and downloads using both the UI and Python client with various file types, including PNG, OWL, CSV, and XLSX. The download links now function correctly for all tested file types.

Based on these tests, the fix appears to be effective. ✅

**Review by mswertz — CHANGES_REQUESTED** [review]
Maybe my test uncovers a  unrelated issue:

For example, I would expect html files and impages to simply be served instead of downloaded. @jelmerveen is also trying this for the VIP reports in RD3.

I tested by uploading this file
https://molgenis.github.io/vip/vip_giab_hg001.html#/samples/0/variants
to [preview](https://preview-emx2-pr-4883.dev.molgenis.org/pet%20store/tables/#/User)

Then its URL is https://preview-emx2-pr-4883.dev.molgenis.org/pet%20store/api/file/User/picture/170620968b30412dbe65b40675d4be5a 

Shouldn't we make it adding the known extension like this?
https://preview-emx2-pr-4883.dev.molgenis.org/pet%20store/api/file/User/picture/170620968b30412dbe65b40675d4be5a.html

Or might it be that we force the download and that we should simply open the link in a new browser window? The code now uses 'attachment' and that might screw things up?

**Comment by harmbrugge** [comment]
> Shouldn't we make it adding the known extension like this? https://preview-emx2-pr-4883.dev.molgenis.org/pet%20store/api/file/User/picture/170620968b30412dbe65b40675d4be5a.html

And don't think we even have to add the extension to the url, by setting the content type and filename correctly the browser will pick up on it.

I changed the content disposition header to inline. I think this will give you the desired behaviour. I tested this with a png which resulted in the file te be shown. The .owl file, from Fernanda's example in the issue, prompted a file download.

**Comment by jelmerveen** [comment]
I tested it with a VIP report and that works! 
Perhaps It would be better to have it open in a target="_blank"

https://preview-emx2-pr-4883.dev.molgenis.org/testUpload/api/file/Versions/sourceFile/e348953ebc2b4907bfdefd92e28f1d61

**Review by Fernananas — APPROVED** [review]
Tested and approved. Everything works as expected!

File: apps/molgenis-components/src/components/tables/cellTypes/FileDisplay.vue [hunk 1]
```diff
@@ -1,5 +1,9 @@
 <template>
-  <a v-if="data.id" :href="data.url">
+  <a
+    v-if="data.id"
+    :href="data.url"
+    :target="data.extension.toLowerCase() == 'html' ? '_blank' : null"
```
Comment (mswertz) [inline apps/molgenis-components/src/components/tables/cellTypes/FileDisplay.vue:5]: does _blank also work for images? I.e. I would propose that we always do '_blank' or does that result in weird situations?

**Review by mswertz — APPROVED** [review]
