### PR TITLE
fix: improved ontology loading in options menu

### LINKED ISSUE #2898: Large ontologies cannot always be loaded when adding or editing row in table
**What version of EMX2 are you using (see footer)**
v8.220.2

**Describe the bug**
Within the insert/update dialog, clicking the edit field for a column that references a large ontology such as _Diseases_ sometimes results in seemingly waiting forever for the list to load. It appears (see screenshot) that a 404 error is raised and that the list could not even be fetched. Sometimes the lists do load, but after a long wait (10+ seconds).
Additionally, closing the edit dialog often results in being signed out from the server.

**To Reproduce**
1. Go to an EMX2 server with Cohorts staging areas
2. Click on a Cohorts staging area
3. Sign in as a user with sufficient permissions to edit data on the schema
4. Click on the table _Subcohorts_
5. Click on the _add entry_ button
6. Click on the field _main medical condition_
7. See error

**Expected behavior**
The ontology list should appear instantaneously after clicking the dropdown menu.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 118.0.2

**Additional context**

### PR DESCRIPTION
**Pull request by YpeZ**
Fixes #2898 by reducing the amount of data queried from the server.

Created function `fetchOntologyOptions` specifically for fetching ontology table for an ontology options list.
* fetchOntologyOptions generates a lean query to fetch an ontology without definition, ontologytermURI, nested parent/child data, mg metadata, etc.
* function is implemented in client.ts, IClient.ts, InputOntology.vue

### CODE REVIEW

**Comment by YpeZ** [comment]
Tried to create an entry in Cohorts on the _TestStagingCohorts_ schema I created on the preview server, but faced 
`TypeError: this.data is undefined` and the entry is not visibile in the Cohorts table.

The entries, however, do show up in _Resources, Extended Resources,_ and _Data Resources_

**Review by mswertz — APPROVED** [review]

File: apps/molgenis-components/src/client/client.ts [hunk 1]
```diff
@@ -320,6 +323,34 @@ const fetchTableData = async (
   return resp?.data.data;
 };
 
+const fetchOntologyOptions = async (
+  tableName: string,
+  schemaName: string | undefined
+) => {
```
Comment (connoratrug) [inline apps/molgenis-components/src/client/client.ts:329]: could type the response as we know the return type in this case

**Review by connoratrug — APPROVED** [review]
