### PR TITLE
fix: when using subclasses should not be able to remove data when it is referred to

### LINKED ISSUE #3144: Reflinks are broken, able to remove data that is referred to
**What version of EMX2 are you using (see footer)**
10.14.0, also 10.9.0

**Describe the bug**
I can delete a row in Variables, which is referred to from Variable values. I cannot reproduce the issue with other tables that have references between them, it seems specific for this reference??? It is not data model related, see pic: 
image

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/
2. Click on catalogue-demo and log in
3. Go to variable values and see that variable 'rmcmes_0' from ATHLETE_CDM has some values associated with it.
4. Go to Variables and delete variable 'rmcmes_0' from ATHLETE_CDM
5. See in Variable values table that the values associated with this deleted variable are still there, but have an empty column 'variable' (see pic for values of another removed variable). This should not happen, because it is part of the composite key of this table.  
image

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mswertz**
closes #3144 

to my amazing we didn't use primary keys, but unique, and also no foreign key from subclass to superclass tables.
this PR fixes both (and I noticed a test that already noticed the suspicious behaviour causing #3144).

how to test:
- to reproduce issue, you should delete a row in Variable that is used in a mapping or variable value via 'All variables'
- before this fix, you could to this because All Variables was not deleted
- with this fix you get a foreign key error prohibiting this delete as it should be

todo:
- [x] added tests
- [x] somebody else verify that 3144 indeed is fixed
- [x] enable to rename primary key fields (required some magic to also change in subclass tables)
- [x] added migration script 17 for old schema missing this fkey

### CODE REVIEW

File: backend/molgenis-emx2-io/src/test/java/org/molgenis/emx2/io/TestRenameAndDelete.java [hunk 1]
```diff
@@ -50,10 +50,10 @@ public void testRenameAndDrop() {
     store = new TableStoreForCsvInMemory();
     store.writeTable(
         "molgenis",
-        List.of("tableName", "columnName", "oldName"),
+        List.of("tableName", "columnName", "oldName", "key"),
```
Comment (mswertz) [inline backend/molgenis-emx2-io/src/test/java/org/molgenis/emx2/io/TestRenameAndDelete.java:53]: should have been a bug before, found it now because we started to add primary keys

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestTruncate.java [hunk 2]
```diff
@@ -62,10 +62,10 @@ public void testTruncate() {
     assertEquals(2, table2.retrieveRows().size());
     assertEquals(1, table3.retrieveRows().size());
 
-    table2.truncate(); // leaves subclass?!!! is this expected behavior?
+    table2.truncate();
```
Comment (mswertz) [inline backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestTruncate.java:65]: so the bug was known!

File: backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java [hunk 3]
```diff
@@ -204,6 +217,29 @@ public void testExtends() {
...
 
+    // verify that you can't delete a parent row when having child rows that are refered to,
+    // regression #3144
+    try {
+      employee.delete(row("fullName", "Katrien Duck"));
+      // refered to by the manager
+      fail("should not be able to delete inherited rows when having reference");
+    } catch (Exception e) {
+      assertTrue(e.getMessage().contains("foreign key"));
+      System.out.println("Errored correctly: " + e.getMessage());
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java:228]: maybe remove to keep clean log during test

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnExecutor.java [hunk 4]
```diff
@@ -91,6 +92,39 @@ static void executeAlterName(DSLContext jooq, Column oldColumn, Column newColumn
...
       }
     }
+    // also apply to subclasses if pkey (using sql otherwise too expensive)
+    if (newColumn.isPrimaryKey() && newColumn.getTable().getColumn(MG_TABLECLASS) != null) {
+      TableMetadata rootTable = newColumn.getTable();
+      List<Record> tableList =
+          jooq
+              .fetch(
+                  """
+                    WITH RECURSIVE RecursiveCTE AS (
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnExecutor.java:102]: CTE ?  Suggest to extract query string to named const instead of inline

**Review by connoratrug — APPROVED** [review]
issue is fixed, code readability/maintainability could be improved by using named functions/constants
