### PR TITLE
fix: EQUALS not supported for type EMAIL

### LINKED ISSUE #1631: cannot edit table that has email as key
**What version of EMX2 are you using (see footer)**
8.115.1

**Describe the bug**
When i try to edit a row from a table that has an email type column as key i get an error 
Screenshot 2022-09-22 at 08 49 04

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org
2. Create table that has a email column as key
3. Add a row to the table
4. Try to edit the row

**Expected behavior**
The now key field can be edited without error

### PR DESCRIPTION
**Pull request by mswertz**
closes #1631

### CODE REVIEW

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java [hunk 1]
```diff
@@ -460,7 +460,7 @@ private List<Condition> jsonFilterQueryConditions(
                 whereCondition(
                     c.getTableName(),
                     c.getName(),
-                    c.getColumnType(),
+                    c.getColumnType().getBaseType(),
```
Comment (connoratrug) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java:463]: unclear to me when to use baseType en when to use type , maybe would be more OO to have object handle this internally instead of caller
