### PR TITLE
fix: catalogue header query

### LINKED ISSUE #4234: ‘Variables’ is missing from the top ribbon for a network of networks.  See $testCatalogue/testNetworkofNetworks. (test 1 step 8)

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #4234

What are the main changes you did:
- explain what you changed and essential considerations.

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: apps/nuxt3-ssr/components/content/ContentBlockCatalogues.vue [hunk 1]
```diff
@@ -31,23 +31,40 @@ const props = defineProps<{
           "
         >
           <TableCell class="hidden sm:table-cell">
-            <div class="items-center flex justify-center w-32">
-              <img :src="catalogue.network?.logo?.url" />
-            </div>
+            <NuxtLink
+              :to="`/${route.params.schema}/ssr-catalogue/${catalogue.network.id}`"
```
Comment (mswertz) [inline apps/nuxt3-ssr/components/content/ContentBlockCatalogues.vue:35]: will we not get into trouble with hardcoding the 'ssr-catalogue' part?

File: apps/nuxt3-ssr/playwright.config.ts [hunk 2]
```diff
@@ -26,10 +18,14 @@ export default defineConfig({
   /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
   use: {
     /* Base URL to use in actions like `await page.goto('/')`. */
-    baseURL: process.env.E2E_BASE_URL || "https://emx2.dev.molgenis.org/", // change to specific http://localhost:*/, preview, etc.
+    baseURL: process.env.E2E_BASE_URL || "https://preview-emx2-pr-4236.dev.molgenis.org/", // change to specific http://localhost:*/, preview, etc.
```
Comment (mswertz) [inline apps/nuxt3-ssr/playwright.config.ts:21]: I suppose you dont want PR names here?

**Review by mswertz — APPROVED** [review]
only small comments, see inline
