### PR TITLE
fix: When loading large zip it seems to hang. closes #257 and #302.

### LINKED ISSUE #257: When loading large zip it seems to hang at and (while committing)
**What version of EMX2 are you using (see footer)**
Software version: 6.2.0. Database version: 6.1.1.

**Describe the bug**
When loading large zip it seems to hang at and (while committing)

**To Reproduce**
Download and upload lifecycle example.

**Expected behavior**
Last step should not seem to hang but instead a message 'commiting all data' should be shown.
Unfortunately no way to know how long that takes but we could make time that goes up so user can see the server is still there

**Screenshots**
image

### PR DESCRIPTION
**Pull request by mswertz**
This required better transaction isolation which is achieved by creating a clone of the metadata (Database) and only syncing changes to schema/tables/columns at commit. Alas required many changes.

### CODE REVIEW

File: backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphQLCompositeKeys.java [hunk 1]
```diff
@@ -74,8 +74,9 @@ public void testRefArray() throws IOException {
             + "\n{firstName:\"Donald\",lastName:\"Duck\"}"
             + "\n{firstName:\"Katrien\",lastName:\"Duck\"}"
             + "\n{firstName:\"Katrien\",lastName:\"Mouse\"}"
-            + "\n{firstName:\"Donald\",lastName:\"Mouse\"}"
-            + "\n], RefTable:["
+            + "\n{firstName:\"Donald\",lastName:\"Mouse\"}]){message}}");
+    execute(
```
Comment (mswertz) [inline backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphQLCompositeKeys.java:78]: split because graphql doesn't ensure execution order so sometimes fails

**Comment by mswertz** [comment]
[review 'upload of large zip hangs'](https://trello.com/c/K8ZxBQ0J/138-review-upload-of-large-zip-hangs)

File: backend/molgenis-emx2-io/src/test/java/org/molgenis/emx2/io/TestCohortCatalogueMultipleSchemas.java [hunk 2]
```diff
@@ -59,80 +54,4 @@ public void importTest() throws IOException {
...
-        });
-
-    database.tx(
-        db -> {
-          runImportProcedure(store, source, schema);
-          StopWatch.print("import of data complete");
-        });
-
-    // verify export doesn't throw exceptions
-    Path tempDir =
```
Comment (sidohaakma) [inline backend/molgenis-emx2-io/src/test/java/org/molgenis/emx2/io/TestCohortCatalogueMultipleSchemas.java:116]: Do you cover these tests somewhere else? I can imagine the export test would be valuable to have?

**Review by sidohaakma — COMMENTED** [review]
It looks like adding the schema layer in between which is good I think to decouple the import process from running the application. The feature is working, you can now click around in the application without being delayed by a running import. 
However when I leave the upload page I can not track the progress anymore. So if users are clicking on other buttons during the upload, how do I now when it is finished? In the logging I can keep track of it.

File: backend/molgenis-emx2-io/src/test/java/org/molgenis/emx2/io/TestCohortCatalogueMultipleSchemas.java (hunk 2 above)
Comment (mswertz) [reply backend/molgenis-emx2-io/src/test/java/org/molgenis/emx2/io/TestCohortCatalogueMultipleSchemas.java:116]: There are import/export roundtrip tests at https://github.com/molgenis/molgenis-emx2/blob/master/backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/TestWebApi.java

Comment (mswertz) [reply backend/molgenis-emx2-io/src/test/java/org/molgenis/emx2/io/TestCohortCatalogueMultipleSchemas.java:116]: we could add a few test assertions to verify that state is also correct

**Review by sidohaakma — APPROVED** [review]
