### PR TITLE
fix: in TableMolgenis when item selected in while selection empty you get false

### LINKED ISSUE #2397: bug: when using a ref_array when the array is empty and I add one I got error
**What version of EMX2 are you using (see footer)**
[8.190.0](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.190.0)

**To Reproduce**

* create empty pet store
* try create a user immediately
* then in that user open pet select, add a pet
* in the popup check the select box

**Expected behavior**
* pet is immediately selected

**Describe the bug**
* instead pet is not selected
* and when select then by hand and click save you get error
 
image

### PR DESCRIPTION
**Pull request by mswertz**
closes #2397

Does this have impact in refback or something?

### CODE REVIEW

File: apps/molgenis-components/src/components/tables/TableMolgenis.vue [hunk 1]
```diff
@@ -184,7 +184,10 @@ export default {
       const key = this.getPrimaryKey(row);
       if (this.showSelect) {
         //deep copy
-        let update = deepClone(this.selection);
+        let update = []; //prevent null list
+        if (Array.isArray(this.selection)) {
```
Comment (chinook25) [inline apps/molgenis-components/src/components/tables/TableMolgenis.vue:188]: Could just do `if (this.selection) { ....` this feels a bit like overengineering ;)

**Review by erikzwart — APPROVED** [review]
Unable to reproduce the bug #2397, able to add user directly without pets being filled in prior.
