### PR TITLE
fix: 4315 Using the sort in the central app results infinite loop

### LINKED ISSUE #4315: Using the sort in the central app results infinite loop
**What version of EMX2 are you using (see footer)**
11.16.0

**Describe the bug**
in the central app , on the schema table , sorting the columns results in a infinite loop loop ( in the js code ).
for the table names this is not to bad as most browsers eventually detect the loop and cuttoff the event chain, but in combination with the change log column the js code tries to infinitely update the components which results in max cpu usage for the browser tab 

**To Reproduce**
1. [Go to 'https://emx2.dev.molgenis.org'](https://emx2.dev.molgenis.org/apps/central/#/)
2. Click on the table header ( first time nothing happend as this is as yet unsorted list in the js code )
3. Click on the table header again ( infinite starts, check browser console to see error  ) 

In case of admin and sorting the last update column
1. [Go to 'https://emx2.dev.molgenis.org'](https://emx2.dev.molgenis.org/apps/central/#/)
2. Sign in as admin 
3. Click on the show last update 
4. Click on the the last update table header ( first time nothing happend as this is as yet unsorted list in the js code )
5. Click on the the last update table header again ( browser tablcpu usage hit > 100% and tab locks up)

**Expected behavior**
No  infinite loop , just sorted items

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #4315

What are the main changes you did:
- clone the array before sort as the sort is inline resulting in loop

See issue for details

### CODE REVIEW

File: apps/central/src/components/Groups.vue [hunk 1]
```diff
@@ -263,9 +263,10 @@ export default {
       return filtered;
     },
     sortSchemas(unsorted) {
+      const unsortedCopy = unsorted.slice();
       let sorted = [];
       if (this.sortColumn === "lastUpdate") {
-        sorted = unsorted.sort((a, b) => {
+        sorted = unsortedCopy.sort((a, b) => {
```
Comment (mswertz) [inline apps/central/src/components/Groups.vue:269]: hmm, instead sort server side?

**Review by mswertz — APPROVED** [review]
