### PR TITLE
fix: shouldn't filter on columnType=file (e.g. logo). closes #508

### LINKED ISSUE #508: It shouldn't be possible to filter on Logo under Institutions, Cohorts or any other data item with Logo in its columns
**What version of EMX2 are you using (see footer)**
8.8.0

**Describe the bug**
If I choose Logo to filter on in Institutions, Cohorts or anywhere else which has Logo in its columns, I see ERROR under that filter (because it's technically impossible to filter on an image).

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/cohorts
2. Click on Filters
3. Scroll down to Logo and select it
4. Click outside the Filter selection box
5. Scroll down to where you can input data for the Logo filter
6. Here you see ERROR

**Expected behavior**
It shouldn't be possible to filter on Logo.

**Screenshots**
If applicable, add screenshots to help explain your problem.  (not necessary, it's self-explanatory, I think)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Versie 92.0.4515.159 (Officiële build) (64-bits)

### PR DESCRIPTION
**Pull request by mswertz**
to test: open a table that has columnType=FILE and see that you cannot show filter for it.

### CODE REVIEW

File: apps/styleguide/src/tables/ShowHide.vue [hunk 1]
```diff
@@ -17,28 +17,30 @@
         )
       </b>
       <div v-for="(col, key) in columns" :key="key">
-        <b class="ml-0" v-if="col.name == 'mg_draft'">
```
Comment (mswertz) [inline apps/styleguide/src/tables/ShowHide.vue:20]: I only added a span around it, but thanks to indent it looks like a massive change

**Review by sidohaakma — APPROVED** [review]
