### PR TITLE
fix: added inheritance join to column in subquery

### LINKED ISSUE #4955: GraphQL query fails when retrieving data from an extended table
### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

Software version: v11.80.0. Database version: 25.

### Description

When I try to retrieve data via graphQL of an extended table, the query fails with the message that the extended column does not exist. 

### Reproduction steps

1. Go to https://erdera.molgeniscloud.org/
2. Go to the 'test' database. 
3. Go to the graphQL 
4. copy and paste this query: 

query {
  Individuals(
    filter: {
      clinicalObservations: { individual: { id: { equals: "Case1C" } } }
    }
  ) {
    id
    # Add other fields you want to retrieve
  }
}

5. Click on the play button and see the error message.

### Expected behaviour

Instead of getting the error I expected the ID to be returned for individual Case1C. 

### System configuration

- Device: 
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by harmbrugge**
Fixes #4955 

### What are the main changes you did
- Added an extra join when for inherited tables.

### How to test
- See issue #4955 

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Review by willemijn-oudijk — APPROVED** [review]

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java [hunk 1]
```diff
@@ -1595,7 +1595,7 @@ private Condition whereColumnInSubquery(Column c, SelectSelectStep subQuery) {
         return row(pkey)
```
Comment (mswertz) [inline backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java:1595]: Ah, I think we should here have the 'root' table instead of the refTable.
The root table has the primary key.
Having this inheritance join indeed fixes it but is more expensive because of all the joining. 
Something like getRefTable().getRootTable() would be best

**Review by mswertz — CHANGES_REQUESTED** [review]

File: backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java (hunk 1 above)
Comment (harmbrugge) [reply backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java:1595]: Yes you're right, thanks
