### PR TITLE
fix(forms): can save draft when errors exist

### LINKED ISSUE #2366: Should be able to save 'draft' when errors exist
**What version of EMX2 are you using (see footer)**
vxx.yy.zz

**Describe the bug**
I tried to save record with errors as draft and couldn't. Whole point of draft is that errors are allowed!

**To Reproduce**
Go to Pet and try to save with errors

**Expected behavior**
Draft button is enabled when primary key is set, even when errors exist
Save button is only enabled when primary key is set and NO errors exist

**Screenshots**
image

### PR DESCRIPTION
**Pull request by mswertz**
point of draft is that it can be saved with errors, however, primary key is required

closes #2366

### CODE REVIEW

File: apps/molgenis-components/src/components/forms/EditModal.vue [hunk 1]
```diff
@@ -204,6 +205,20 @@ export default {
         };
       });
     },
+    saveDraftDisabledMessage() {
+      if (
+        this.tableMetaData?.columns.some(
+          (c) =>
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/EditModal.vue:211]: It's good practice to avoid 1 letter variables

File: apps/molgenis-components/src/components/forms/EditModal.vue [hunk 2]
```diff
@@ -204,6 +205,20 @@ export default {
...
+            c.key == 1 &&
+            c.columnType != "AUTO_ID" &&
+            this.rowData[c.id] == null
+        )
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/EditModal.vue:215]: === and !== :)

File: apps/molgenis-components/src/components/forms/EditModal.vue [hunk 3]
```diff
@@ -204,6 +205,20 @@ export default {
...
+      ) {
+        return "Cannot save draft: primary key is required";
+      } else {
+        return null;
+      }
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/EditModal.vue:220]: It think it's better for these kind of variables to have '' (empty string) as the 'no error'-value, since empty string is also falsy and it makes the typing way less complicated.

**Review by chinook25 — CHANGES_REQUESTED** [review]

**Review by chinook25 — APPROVED** [review]
