### PR TITLE
fix: Move streaming after headers. closes #1211

### LINKED ISSUE #1211: When downloading a zip file from the tables or Up/Download page the file is downloaded without the schema name
**What version of EMX2 are you using (see footer)**
8.66.0

**Describe the bug**
When you go to the tables page in a database and click on the 'download all tables zip' link, you get a file with the schema name, but sometimes the file is downloaded with the name 'zip.zip'. Unclear when this happens.

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org'
2. Click on a schema
3. Navigate to 'tables'
4. Click download all tables 'zip'
5. Do this multiple times, sometimes file with schema name is downloaded, sometimes not.

**Expected behavior**
Download of zip file with schema name

### PR DESCRIPTION
**Pull request by clemens-tolboom**
Headers moved up before generating and streaming content.

Closes #1211

### CODE REVIEW

**Review by connoratrug — APPROVED** [review]
tested on https://preview-emx2-pr-2728.dev.molgenis.org/catalogue-demo/tables/#/ , solves the issue , hard to add test as its dependant on a timing issue

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/ZipApi.java [hunk 1]
```diff
@@ -59,16 +59,15 @@ static String getZip(Request request, Response response) throws IOException {
     tempDir.toFile().deleteOnExit();
     try (OutputStream outputStream = response.raw().getOutputStream()) {
       Schema schema = getSchema(request);
+      String fileName = schema.getMetadata().getName() + System.currentTimeMillis() + ".zip";
+      // First set headers before stream blob.
```
Comment (chinook25) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/ZipApi.java:63]: Comment should be removed, as it adds no information. Or it should explain why headers need to be added before the blob.

**Review by mswertz — APPROVED** [review]
Thanks. I feel really stupid screwing up the order of these, not realizing the bytes start to be send immediately when 'write' is called and then it is too late to sent the headers.
