### PR TITLE
fix: 5682 errors should react to visibility changes

### LINKED ISSUE #5682: Form errors do not update in reaction to changes in field visibility
### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

13.70.0

### Description

Something is wrong when fields have visible and validation expressions  subject > leave date of birth empty > 3. Patient Status > choose Dead > save draft > messages appear in date of birth and date of death fields, these are now impossible to remove again. If you enter a date of birth the message ‘! 3.2 Date of death is requiredDate of death is required’ appears. If you then enter a date of death, the message in the date of birth fields remains the same and the message ‘! Date of death is required’ appears at the date of death field.

### Reproduction steps

subject > leave date of birth empty > 3. Patient Status > choose Dead > save draft > messages appear in date of birth and date of death fields, these are now impossible to remove again. If you enter a date of birth the message ‘! 3.2 Date of death is requiredDate of death is required’ appears. If you then enter a date of death, the message in the date of birth fields remains the same and the message ‘! Date of death is required’ appears at the date of death field.

### Expected behaviour

If a field that contains an error becomes invisible the error should be removed from the form error, i.e no longer be shown / counted  

### System configuration

_No response_

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #5682 

### What are the main changes you did
- instead of exposing non-reactive read/write error map, expose read-only-reactive-errors-on-visible-fields-map

### How to test
- see #5682 

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: apps/tailwind-components/app/composables/useForm.ts [hunk 1]
```diff
@@ -427,6 +427,15 @@ export default function useForm(
     );
   });
 
+  // reactive intersection of visible columns and error columns
```
Comment (chinook25) [inline apps/tailwind-components/app/composables/useForm.ts]: comment not needed

**Review by chinook25 — APPROVED** [review]
