### PR TITLE
fix: table explorer showed schemas from other schemas. closes #3022"

### LINKED ISSUE #3022: Duplicate tables in schemas with references to another schema
**What version of EMX2 are you using (see footer)**
10.4.0

**Describe the bug**
Tables within a schema are duplicated. Seems to only be the case when the datamodel contains references to another schema (refSchema) and to tables that are not ontology tables.
image

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/test_staging/tables/#/
2. See that some, but not all, tables are duplicated
3. This is also the case in the up/download section: https://emx2.dev.molgenis.org/test_staging/updownload/
4. Only happens when there are references to non ontology tables in another schema.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #3071: Table view breaks for multiple tables in staging areas of catalogue
**What version of EMX2 are you using (see footer)**
10.5.2

**Describe the bug**
Some tables cannot be viewed in catalogue staging areas.
image

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/apps/central/#/ and sign in
2. Click on testCohort, which is a staging area for a cohort
3. Click on Cohorts to enter the cohorts table. 
You can also directly go to https://emx2.dev.molgenis.org/testCohort/tables/#/Cohorts

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mswertz**
closes #3071

todo:
- [x] check that tables from other schemas are filtered in cases that is needed
- [x] check that #3071 works now

Sorry to have wasted your time with 'fundamental decisions' as you can see original bugfix was only 1 line.

### CODE REVIEW

File: apps/tables/src/components/ListTables.vue [hunk 1]
```diff
@@ -74,7 +74,9 @@ export default {
             )
           );
       } else {
-        return this.schema.tables;
+        return this.schema.tables.filter(
```
Comment (connoratrug) [inline apps/tables/src/components/ListTables.vue:77]: what about https://github.com/search?q=repo%3Amolgenis%2Fmolgenis-emx2%20schema.tables&type=code  , everywhere the schema.tables is used this filter should be added ?

the endPoint result changes, i woud expect a change in at least one of the api endpoint test that checks for this change

Comment (connoratrug) [reply apps/tables/src/components/ListTables.vue:77]: for example: image

**Comment by mswertz** [comment]
indeed, I also had expected a failing test. apparently this and the previous state is not under test. I don't have time to fix that now so either we accept this (assuming there is no other issues) or this has to wait until monday.

**Comment by mswertz** [comment]
I agree that we can do this better. But I would like to first revert.
And indeed we would need a better QC process so side effects of bugfixes can be found sooner
(and as a matter of principle, lets fix bugs without major refactorings if we can, that is root cause)
