### PR TITLE
Fix/ref binding to form

### LINKED ISSUE #4746: fix: selected ref value should be visible to user when opening a form
### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

11.63.0

### Description

Selected ref value should be visible to user when opening a form 

### Reproduction steps

For example go to: https://emx2.dev.molgenis.org/apps/tailwind-components/#/Form.story?schema=pet+store&table=Pet

Select the first row

### Expected behaviour

Assuming the row has the value 'cat' for the field 'category'  i would expect the 'cat' radiobox to be selected 

### System configuration

- Device: 
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by connoratrug**
### What are the main changes you did
- fix the binding of the row data to the form for ref component
- extend the form story to include the selectedRow in the query
- add to test for verify the data from the selected row in shown in the form 

### How to test
- see issue 
Closes #4746

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Review by davidruvolo51 — APPROVED** [review]

File: apps/tailwind-components/components/input/Ref.vue [hunk 1]
```diff
@@ -88,6 +88,31 @@ onMounted(async () => {
   initialCount.value = count.value;
 });
 
+// the selectionMap is not reactively bound to the model due to need to fetch the options asynchonously
+watch(
+  () => modelValue.value,
+  () => {
+    if (props.isArray === false) {
```
Comment (mswertz) [inline apps/tailwind-components/components/input/Ref.vue:95]: this only fires on change right? 

I think we have another issue because the template might be using fields not in the modelValue (because that might be pkey) so applyTemplate is not enough. Sadly, we would need to retrieve the rows based on the primary key to ensure we can render. We really need to see if we can move the templates to server side because this is getting quite expensive.

File: apps/tailwind-components/pages/Form.story.vue [hunk 2]
```diff
@@ -119,10 +125,22 @@ watch(
 watch(
   () => rowIndex.value,
   async () => {
+    const query: { schema: string; table: string; rowIndex?: number } = {
```
Comment (mswertz) [inline apps/tailwind-components/pages/Form.story.vue:128]: interestingly, this row select is actually a very good test case for the Ref input. So once we have implemented the 'select' display for the Ref we should replace it.

**Review by mswertz — COMMENTED** [review]
We must test for the case where the modelValue contains only the pkey, while the refLabel actually requires other columns of that row.

Directory-demo has examples of refLabel.

N.B. during retrieval we now usually retrieve expanded columns to address this use case. So we can gamble that in practice it never happens.
