### PR TITLE
fix: unescape order by args

### LINKED ISSUE #1539: Sort on an attribute with underscore fails
EMX2 version 8.112.8

When in table view, clicking the attribute name normally sorts that column. But when the attribute contains an underscore this fails. Examples of errors being thrown:

For a 'long' datatype named 'position_start':
`Error: Exception while fetching data (/GenomicVariations) : Query failed: Column 'position__start' is unknown in table GenomicVariations`

For a 'string' datatype named 'position_assemblyId':
`Error: Exception while fetching data (/GenomicVariations) : Query failed: Column 'position__assemblyId' is unknown in table GenomicVariations`

Obviously this has something to do with the underscore escaping from/to GraphQL.

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #1539

### CODE REVIEW

File: backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java [hunk 1]
```diff
@@ -605,7 +605,12 @@ private DataFetcher fetcherForTableQueryField(Table aTable) {
         q.offset((int) args.get(GraphqlConstants.OFFSET));
       }
       if (args.containsKey(GraphqlConstants.ORDERBY)) {
-        q.orderBy((Map<String, Order>) args.get(GraphqlConstants.ORDERBY));
+        Map<String, Order> orderBy = (Map<String, Order>) args.get(ORDERBY);
+        Map<String, Order> unescapedMap = new HashMap<>();
+        for (var entry : orderBy.entrySet()) {
+          unescapedMap.put(entry.getKey().replace("__", "_"), entry.getValue());
```
Comment (mswertz) [inline backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java:611]: Hmm, I am a bit worried. 

I expected we would have an 'unescape' method to mirror the 'escape' method, with suitable tests
https://github.com/molgenis/molgenis-emx2/blob/4880b49b7496870209860b68ad3a9c767637645e/backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java#L44

So minimally you need
- "replaceAll" and 
-  replace "_" with " ".

However, apparently we have solved this elsewhere in a different way. We used  ```findColumnById(aTable, s.getName());``` to check whether the column actually exists, and then to find its name. Because I remember the 'unescape' might not be deterministic (in theory) because '__' might come from a '_' or two spaces '  '.

See most ugly code in whole of emx2 here findColumnById is used for unescaping the query
https://github.com/molgenis/molgenis-emx2/blob/4880b49b7496870209860b68ad3a9c767637645e/backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java#L525

For filters there is analogously ugly code here
https://github.com/molgenis/molgenis-emx2/blob/4880b49b7496870209860b68ad3a9c767637645e/backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java#L440

So I suppose we need something like that for orderBy which I hope may be much simpler, and therefore most shorter? Or we might want to exand the 'filter' code to also apply to sort parameter?

**Review by mswertz — CHANGES_REQUESTED** [review]

File: backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java (hunk 1 above)
Comment (connoratrug) [reply backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java]: i think the above is incorrect , i have added a test and moved the unescape to a function ( not really needed imo as it really context dependant ). The unescape is a lot simpler than the escape. Please add a failing test case if you think some thing is missing

**Review by mswertz — APPROVED** [review]
I have updated the code to use "findColumnById" and moved the test to the other place where names with spaces are tested.

**Comment by mswertz** [comment]
lets wait if build gets green, than we can merge

File: backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqSchemaFields.java [hunk 2]
```diff
@@ -465,18 +465,34 @@ public void testNamesWithSpaces() throws IOException {
...
-          "mutation{insert(Person_details:{First_name:\"blaat\",Last_name:\"blaat2\"}){message}}");
+          "mutation{insert(Person_details:{First_name:\"blaatb\",Last_name:\"blaatb2\"}){message}}");
       TestCase.assertEquals(
           count + 1,
           execute("{Person_details_agg{count}}").at("/Person_details_agg/count").intValue());
+
+      // order by should work with spaces
+      TestCase.assertEquals(
+          "blaata",
+          execute("{Person_details(orderby:{First_name:ASC}){First_name}}")
```
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqSchemaFields.java:483]: Added a test for the __ to _ escaping.
