### PR TITLE
fix: add hyperlink input

### LINKED ISSUE #3823: fix:(platform) InputEmail and InputHyperlink should be used for column type === email or hyperlink respectively.
todo:
- [ ] check and fix FormInput.vue and ArrayInput.vue
- [ ] test??

### PR DESCRIPTION
**Pull request by chinook25**
What are the main changes you did:
- added hyperlink input to molgenis components
- closes #3823 
- also did some lay-outing

how to test:
- go to the styleguide
- go to InputHyperlink
- try some hyperlink variations
- add a hyperlink to a schema
- check in forms that it works there as well

todo:
- [ ] updated docs in case of new feature
- [x] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: apps/molgenis-components/src/components/forms/InputHyperlink.vue [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+    :id="id"
+    :label="label"
+    :required="required"
+    :description="description"
+    :errorMessage="stringError"
+  >
+    <InputGroup>
+      <template v-slot:prepend>
+        <slot name="prepend"></slot>
+      </template>
```
Comment (chinook25) [inline apps/molgenis-components/src/components/forms/InputHyperlink.vue:12]: @mswertz I copied this from the InputEmail, but are these needed here (and for email?) or can they be omitted?

Comment (mswertz) [reply apps/molgenis-components/src/components/forms/InputHyperlink.vue:12]: this was meant if we would like to include an icon. Probably we can do this better in the future.

**Review by mswertz — APPROVED** [review]
