### PR TITLE
fix: timeout destroyed session instead of invalidating. fixes #328, fixes #345

### LINKED ISSUE #328: session timing out - unable to see data
**What version of EMX2 are you using (see footer)**
6.7.1
**Describe the bug**
After first being able to see data in the Catalogue app, the data is not visible anymore.

**To Reproduce**
1. Go to https://emx2.test.molgenis.org/UMCG%20Data%20Catalogue/catalogue/#/
2. Wait a while
3. Click on Catalogue
4. Unable to see data - you have to log in..... (also when schema is public...)

**Expected behavior**
Still being able to see data

### LINKED ISSUE #345: Can not view catalog data
**What version of EMX2 are you using (see footer)**
6.8.0

**Describe the bug**
While browsing the catalogue i get the message "You have to login to view the data."
I can no longer view any data  

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/'
2. Catalogue_test
3. click the molgenis logo top left

**Expected behavior**
See the catalogue data or an ui element that guides me towards the data

### PR DESCRIPTION
**Pull request by mswertz**
fixes #328, fixes #345

It was difficult to reproduce the behavior because error is infrequent.  In my experience quickly bouncing around in the app can trigger the issue within 10 clicks. It then in error creates a new session while session already exists.

In the solution the code that creates session is simplified, removing the weird 'after the request' part that took care of session creation, and also ensuring that even if parallel requests would trigger session creation simply the last 'wins' without disturbing other requests.

Also there is now a way to inject tokens in the session list, currently only used for tests (to be expanded to proper token management later). This removes potential security issues with that.

### CODE REVIEW

**Comment by mswertz** [comment]
I still get now and then this error so it is not all nice and dandy
image

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/AppsProxyService.java [hunk 1]
```diff
@@ -118,7 +118,7 @@ private static Object handleRequest(Request req, Response res) throws IOExceptio
     res.status(proxyResponse.code());
 
     // return result
-    return res.raw();
+    return res.body();
```
Comment (mswertz) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/AppsProxyService.java:121]: this has to do with the interference with session management otherwise.

**Comment by mswertz** [comment]
> SonarCloud Quality Gate failed.    ![Quality Gate failed]

I will check to see if I can add the necessary tests, if you can review?

**Comment by sidohaakma** [comment]
[timeout destroyed session instead of invalidating](https://trello.com/c/sxB9vxZI/183-timeout-destroyed-session-instead-of-invalidating)

**Comment by mswertz** [comment]
> > SonarCloud Quality Gate failed.    ![Quality Gate failed]
> 
> I will check to see if I can add the necessary tests, if you can review?

I have updated the tests to also have a few tests that use the session mechanism instead of token mechanism. Unfortunately this required TestWebApi to have many times 'token()' added. Sorry for code explosion there.

**Comment by sidohaakma** [comment]
> > > SonarCloud Quality Gate failed.    ![Quality Gate failed]
> > 
> > 
> > I will check to see if I can add the necessary tests, if you can review?
> 
> I have updated the tests to also have a few tests that use the session mechanism instead of token mechanism. Unfortunately this required TestWebApi to have many times 'token()' added. Sorry for code explosion there.

**Review by sidohaakma — COMMENTED** [review]
Is the `TestWebApi` sufficient to test the `MolgenisSessionManager`? Or do we need additional testing on the class?  In my head it is still hard to understand all the stuff that is done on the high level `TestWebApi`. However if this catches all the stuff around the webapi it should be sufficient. This bug is maybe a sign to dive in a bit deeper.

Besides this I do not think this is threadsafe at the moment. Using `request.session().isNew()` handles threadsafety. We can wrap the whole `getSession`-method in that check to make it threadsafe?

**Comment by mswertz** [comment]
> Is the `TestWebApi` sufficient to test the `MolgenisSessionManager`? Or do we need additional testing on the class? In my head it is still hard to understand all the stuff that is done on the high level `TestWebApi`. However if this catches all the stuff around the webapi it should be sufficient. This bug is maybe a sign to dive in a bit deeper.
> 

this test is mainly smoke test because web api is mainly facade on lower level functions that are tested seperately. Exception is session part. I think it will be wasteful to add many tests here without known bugs that motivate them.

> Besides this I do not think this is threadsafe at the moment. Using `request.session().isNew()` handles threadsafety. We can wrap the whole `getSession`-method in that check to make it threadsafe?

I did not think thread safety is an issue (worst case session attribute is updated unnecessarily) but do you think otherwise? In any case happy if we can improve this using isNew. Do you make proposal or should I?

**Review by sidohaakma — CHANGES_REQUESTED** [review]

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 2]
```diff
@@ -7,97 +7,78 @@
...
   public static final String MOLGENIS_TOKEN = "x-molgenis-token";
-  private static final String SESSION_ATTRIBUTE = "session";
+  private static final String SESSION_ATTRIBUTE = "molgenis_session";
   private static final Logger logger = LoggerFactory.getLogger(MolgenisSessionManager.class);
+  private static final int SESSION_TIMEOUT = 30;
 
-  // key is the user, might lead to trouble
+  // map so we can track the sessions
+  // session id is the key, todo in case of session less requests outside browser
   private Map<String, MolgenisSession> sessions = new LinkedHashMap<>();
```
Comment (fdlk) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:23]: LinkedHashMap is not threadsafe!

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 3]
```diff
@@ -7,97 +7,78 @@
...
-        logger.info(
-            "Changed session from old user({}]) to new user({}) because login changed",
-            session.getSessionUser(),
-            newSession.getSessionUser());
-      }
+    // get the session
+    MolgenisSession session = request.session().attribute(SESSION_ATTRIBUTE);
+
+    // check session is invalid
+    if (minutesBetween(session.getCreateTime(), DateTime.now())
```
Comment (fdlk) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:50]: If I understand correctly, the MolgenisSession has its own timeout mechanism, besides the existing servlet engine session? Why is this needed?

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 4]
```diff
@@ -12,92 +12,78 @@
...
+    MolgenisSession session = createSession(request.session().id());
+
+    // put in request session so we can easily access for this session
+    request.session().attribute(SESSION_ATTRIBUTE, session);
+
+    // return
+    return session;
+  }
+
+  public MolgenisSession createSession(String token) {
```
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:68]: This is done to enable test to setup session, probably can be made friendly

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 5]
```diff
@@ -12,92 +12,78 @@
...
-        }
-
-      } else {
-        logger.info("Reusing session for user({})", session.getSessionUser());
-        // refresh timeout
-        session.setCreateTime(DateTime.now());
-        return session;
-      }
-    }
+          .isGreaterThan(Minutes.minutes(SESSION_TIMEOUT))) {
```
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java]: Why? How?

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 6]
```diff
@@ -12,92 +12,78 @@
...
-        sessions.put(newSession.getSessionUser(), newSession);
-        logger.info(
-            "Changed session from old user({}]) to new user({}) because login changed",
-            session.getSessionUser(),
-            newSession.getSessionUser());
+    // else check if token session
+    // todo, enable persistent tokens beyond session lifetime
+    else if (request.headers(MOLGENIS_TOKEN) != null) {
+      String token = request.headers(MOLGENIS_TOKEN);
+      if (sessions.containsKey(token)) {
```
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:32]: This is only to enable testing, not as full token mechanism

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 7]
```diff
@@ -12,92 +12,78 @@
...
   private Map<String, MolgenisSession> sessions = new LinkedHashMap<>();
 
   public MolgenisSessionManager() {}
 
   public MolgenisSession getSession(Request request) {
-    // already in a session, then return that
+
+    // check if already in session
     if (request.session().attribute(SESSION_ATTRIBUTE) != null) {
       MolgenisSession session = request.session().attribute(SESSION_ATTRIBUTE);
```
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java]: I assume session id are always unique, do you think that is not the case?

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 8]
```diff
@@ -12,92 +12,78 @@
...
-          return session;
-        });
-  }
+        logger.info(
+            "Invalidating session for user({}) because timeout more than {} mins",
+            session.getSessionUser(),
+            SESSION_TIMEOUT);
+
+        // invalidate the session by signing out
+        session.getDatabase().setActiveUser("anonymous");
```
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java]: I think you now ask for a new feature, I dont want to expand scope of this pull request unneeded

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 2 above)
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:23]: How will this lead to problems here?

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 3 above)
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:50]: Good question, the session timeout cannot be changed (unless we go configure Jetty). So this seemed easier. Might be unneeded if jetty timeout is also 30mins. You point to another issue which is to remove timed out sessions from session map.

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 9]
```diff
@@ -7,97 +7,78 @@
...
-              "Destroyed session for user({0}) because timeout more than 30mins",
-              session.getSessionUser());
-        }
-
-      } else {
-        logger.info("Reusing session for user({})", session.getSessionUser());
-        // refresh timeout
-        session.setCreateTime(DateTime.now());
-        return session;
+  public synchronized MolgenisSession getSession(Request request) {
```
Comment (fdlk) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:27]: This is the easiest way to make things threadsafe but means the session manager can only look up one session at a time, which hurts performance for concurrent requests

Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:27]: I believe we dont really need to make it synchronized; instead we can use an optimistic approach where session object might be set more than once

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 2 above)
Comment (fdlk) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:23]: The inserts are done in a synchronized method but may run in parallel with reads done by clearAllCaches method which is not synchronized.

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 3 above)
Comment (fdlk) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:50]: Best leave session timeouts up to the servlet container. I think the servlet API has a session listener interface where you can listen for session timeouts.

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 10]
```diff
@@ -12,92 +12,78 @@
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 import spark.Request;
-import spark.Response;
 
 public class MolgenisSessionManager {
   public static final String MOLGENIS_TOKEN = "x-molgenis-token";
-  private static final String SESSION_ATTRIBUTE = "session";
+  private static final String SESSION_ATTRIBUTE = "molgenis_session";
```
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:17]: agreed

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java]: rewrote to let jetty session manager create and destroy the sessions completely via HttpSessionListener

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java]: session manager will now invalidate the session completely.

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 2 above)
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:23]: changed to ConcurrentHashMap, will that help?

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 3 above)
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:50]: rewrote to use let jetty take care of the timeouts.

File: backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/TestWebApi.java [hunk 11]
```diff
@@ -30,6 +31,7 @@
 
   public static final String DATA_PET_STORE = "/pet store/api/csv";
   public static final String PET_SHOP_OWNER = "pet_shop_owner";
+  public static final String TOKEN_ADMIN = "admin";
```
[the remark this answers is not in the document]
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/TestWebApi.java:34]: > This is the sessionId value maybe make it more explicit.

renamed to sessionid

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 9 above)
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java]: refactored to let jetty take care of session management

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/SessionListeningJettyFactory.java [hunk 12]
```diff
@@ -0,0 +1,69 @@
...
+      StaticFilesConfiguration staticFilesConfiguration,
+      ExceptionMapper exceptionMapper,
+      boolean hasMultipleHandler) {
+    MatcherFilter matcherFilter =
+        new MatcherFilter(
+            routeMatcher, staticFilesConfiguration, exceptionMapper, false, hasMultipleHandler);
+    matcherFilter.init(null);
+    JettyHandler handler = new JettyHandler(matcherFilter);
+    handler.getSessionCookieConfig().setHttpOnly(httpOnly);
+    handler.setMaxInactiveInterval(SESSION_TIMEOUT_SECONDS); // session timeout
```
Comment (fdlk) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/SessionListeningJettyFactory.java:62]: Is this the only reason for the class? If so, the servlet spec allows you to set the timeout in web.xml but also on each session programmatically: session.setMaxInactiveInterval(30*60);

Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/SessionListeningJettyFactory.java:62]: Reason is to add session listener. Timeout is just bonus

Comment (fdlk) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/SessionListeningJettyFactory.java:62]: I found https://github.com/perwendel/spark/issues/1190 so it looks like this is the way to go then

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSession.java [hunk 13]
```diff
@@ -69,7 +62,7 @@ public void clearCache() {
     logger.info("cleared database and caches for user {}", getSessionUser());
   }
 
-  public void setCreateTime(DateTime newTime) {
-    this.createTime = newTime;
+  public String getToken() {
+    return token;
```
Comment (fdlk) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSession.java:66]: No longer needed, I think?

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/SessionListeningJettyFactory.java [hunk 14]
```diff
@@ -0,0 +1,69 @@
...
+import spark.embeddedserver.EmbeddedServerFactory;
+import spark.embeddedserver.jetty.EmbeddedJettyServer;
+import spark.embeddedserver.jetty.JettyHandler;
+import spark.embeddedserver.jetty.JettyServerFactory;
+import spark.http.matching.MatcherFilter;
+import spark.route.Routes;
+import spark.staticfiles.StaticFilesConfiguration;
+
+// copied from EmbeddedJettyFactory
+public class SessionListeningJettyFactory implements EmbeddedServerFactory {
```
Comment (fdlk) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/SessionListeningJettyFactory.java:18]: Maybe add a little comment here that the class is used to add the session listener, since the servlet context is inaccessible for embedded jetty.

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 15]
```diff
@@ -1,103 +1,82 @@
...
-        });
+    // get the session
+    MolgenisSession session = sessions.get(request.session().id());
+    logger.info("get session for user({})", session.getSessionUser());
+    return session;
   }
 
-  void updateSession(Request request, Response response) {
-    MolgenisSession session = getSession(request);
+  MolgenisSession createSession(String token) {
```
Comment (fdlk) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:66]: Remove token parameter here

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java [hunk 16]
```diff
@@ -1,103 +1,82 @@
...
+    // Register custom server to sparkjava that listens to the session changes
+    EmbeddedServers.add(
+        EmbeddedServers.Identifiers.JETTY,
+        new SessionListeningJettyFactory(
+            new HttpSessionListener() {
 
-  public MolgenisSessionManager() {}
+              public void sessionCreated(HttpSessionEvent httpSessionEvent) {
+                // add session into session pool
+                createSession(httpSessionEvent.getSession().getId());
```
Comment (fdlk) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:31]: put session into map here

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSession.java [hunk 17]
```diff
@@ -14,16 +13,14 @@
...
-  private String sessionUser;
+  private String token;
   private Database database;
   private GraphQL graphqlForDatabase;
-  private DateTime createTime;
   private Map<String, GraphQL> graphqlPerSchema = new LinkedHashMap<>();
 
-  public MolgenisSession(Database database) {
+  public MolgenisSession(Database database, String token) {
+    this.token = token;
```
Comment (fdlk) [inline backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSession.java:22]: remove token field here, the MolgenisSession works fine without it

**Review by fdlk — CHANGES_REQUESTED** [review]
The token gets passed around a bit more than it needs to, otherwise looks good to me

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (fdlk) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:50]: Can't the test upgrade the session to admin by sending a login request? Unsure how this works.

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 15 above)
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:66]: agreed

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSession.java (hunk 17 above)
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSession.java:22]: agreed

File: backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java (hunk 16 above)
Comment (mswertz) [reply backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java:31]: agreed

**Comment by mswertz** [comment]
removed token feature completely for now; refactored tests to keep track of session

**Review by fdlk — APPROVED** [review]
