### PR TITLE
fix: emx1 importer should map hyperlink, email and file column types to emx2 equivalents

### LINKED ISSUE #1299: URLs without "https://" in cohorts view don't work
**What version of EMX2 are you using (see footer)**
8.88.1

**Describe the bug**
If a user adds and url in their cohort description without https:// in front of it the url doesn't work.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. Click on 'tables' > 'cohorts'
3. Add an url for a cohort without https:// and the url in the cohorts view is broken
For example: for cohort 'CSC' the url is filled in as _nkcx.se_. If you click on website in the cohorts view (https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/networks-catalogue/HEAP/cohorts) you are redirected to _https://data-catalogue.molgeniscloud.org/public_html/apps/catalogue/nkcx.se_ 
If you fill in _https://nkcx.se_ the url does work.

### PR DESCRIPTION
**Pull request by mswertz**
To test, upload an emx1 file having hyperlink, email and/or file types.

Known limitations: 
* will only fix data model
* not yet: move file data to right place
* you might face stricter validation rules (as hyperlinks MUST start with http or https)

Also

closes #1299

### CODE REVIEW

**Comment by mswertz** [comment]
[[ ]Small fixes on EMX1 to EMX2: hyperlink, file, email types will be added to emx2 model (todo later: files extracted)](https://trello.com/c/kpZ50eIf/1021-small-fixes-on-emx1-to-emx2-hyperlink-file-email-types-will-be-added-to-emx2-model-todo-later-files-extracted)

File: backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/emx1/Emx1.java [hunk 1]
```diff
@@ -187,19 +187,23 @@ private static Map<String, Emx1Entity> loadTables(TableStore store, SchemaMetada
 
   private static ColumnType getColumnType(String dataType) {
     switch (dataType) {
-      case "compound": // todo
+      case "compound": // unsupported, skipped.
```
Comment (jelmerveen) [inline backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/emx1/Emx1.java:190]: Why not let them go to default = string and remove these cases all together until you need them. Then you will see immediately that it is not implemented. Now it is implemented but it goes to a string.

**Review by jelmerveen — CHANGES_REQUESTED** [review]

File: backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/emx1/Emx1.java (hunk 1 above)
Comment (mswertz) [reply backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/emx1/Emx1.java:190]: ah, good point. I can make them map to 'heading', so you would get a title to play with.

**Review by jelmerveen — APPROVED** [review]
