### PR TITLE
fix: an instance of Pet should refer back to the collection of pets with qb:dataSet and not qb:DataSet

### LINKED ISSUE #2931: Incorrect use of qb:DataSet (Class) where qb:dataSet (Property) is meant
**Describe the bug**
We are using qb:DataSet as a predicate, while this should be qb:dataSet (notice lowercase d).

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/catalogue_demo/api/rdf/Datasets'
2. Search for 'qb:DataSet'

**Expected behavior**
We use qb:DataSet to refer back from an item in the dataset to the dataset as a whole. The thing that we refer to with qb:dataSet is an instance of qb:DataSet.

**Actual Result**
```
Catalogue_demo:Datasets a owl:Class;
  rdfs:subClassOf qb:DataSet, sio:SIO_000754, owl:Thing;
  rdfs:label "Datasets";
  dcterms:description "Definition of a dataset within a (common) data model"@en .

<https://emx2.dev.molgenis.org:443/catalogue_demo/api/rdf/Datasets?resource=ANAGRAFICA&name=ANAGRAFICA>
  a Catalogue_demo:Datasets, sio:SIO_001187, qb:Observation;
  qb:DataSet Catalogue_demo:Datasets;
  <https://emx2.dev.molgenis.org:443/catalogue_demo/api/rdf/Datasets/column/resource>
    <https://emx2.dev.molgenis.org:443/catalogue_demo/api/rdf/ExtendedResources/ANAGRAFICA>;
  <https://emx2.dev.molgenis.org:443/catalogue_demo/api/rdf/Datasets/column/name> "ANAGRAFICA";
  <https://emx2.dev.molgenis.org:443/catalogue_demo/api/rdf/Datasets/column/sinceVersion>
    "1.0" .
```

### PR DESCRIPTION
**Pull request by esthervanenckevort**
- test case for verify that the qb:dataSet predicate is used
- use IRI_DATASET_CLASS and IRI_DATASET_PREDICATE to distinguish between the class and the predicate
- fix the rowsToRdf method to use the IRI_DATASET_PREDICATE

Closes #2931

### CODE REVIEW

File: backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java [hunk 1]
```diff
@@ -74,7 +74,10 @@ public class RDFService {
   public static final String NAMESPACE_DCTERMS = "http://purl.org/dc/terms/";
   public static final IRI IRI_DATABASE_TABLE =
       Values.iri("http://semanticscience.org/resource/SIO_000754");
-  public static final IRI IRI_DATASET = Values.iri("http://purl.org/linked-data/cube#DataSet");
+  public static final IRI IRI_DATASET_CLASS =
+      Values.iri("http://purl.org/linked-data/cube#DataSet");
```
Comment (mswertz) [inline backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java:78]: are you sure that we want Dataset as a class? I mean, either stuff is Owl:thing or it is this. But I think it is now both?

**Review by mswertz — APPROVED** [review]
looks good, untested.

File: backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java (hunk 1 above)
Comment (esthervanenckevort) [reply backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java:78]: It can be both, I discussed this with Alexander and he's happy with it.
