### PR TITLE
fix(nuxt3-ssr): fix mobile modal background

### LINKED ISSUE #2560: Incorrect background style in side modal
**What version of EMX2 are you using (see footer)**
8.207.1

**Describe the bug**
Medium with filters size modal has incorrect background style.

**To Reproduce**
Go to cohorts list view, ( for example https://umcgresearchdatacatalogue.nl/UMCG/ssr-catalogue/cohorts/)
Resize page to get filters in popup/modal
Click the 'Filters' button'

**Expected behavior**
Modal style should match the theme style

**Screenshots**
Screenshot 2023-07-26 at 12 21 45

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #2560

add some small ux improvements to the search modal

### CODE REVIEW

File: apps/nuxt3-ssr/components/SearchResultsViewTabsMobile.vue [hunk 1]
```diff
@@ -32,25 +10,20 @@ function toggleMode(detailed) {
...
+        <slot></slot>
+      </ContentBlockModal>
+
+      <template #footer="{ hide }">
+        <Button
+          type="secondary"
+          size="small"
+          label="View results"
+          iconPosition="left"
+          @click="hide()"
```
Comment (mswertz) [inline apps/nuxt3-ssr/components/SearchResultsViewTabsMobile.vue:24]: ok I see, either brilliant or evil but at least very effective :-)

**Review by mswertz — APPROVED** [review]
