### PR TITLE
fix: set manager permission to trigger functions

### LINKED ISSUE #4894: fix(permissions): manager Role Unable to Update Schema
### Have you checked if this issue already exists?

- [x] yes

### Molgenis EMX2 version

Software version: v11.76.3-SNAPSHOT. Database version: 25.

### Description

According to the documentation, the "manager" role is defined as follows:

> **manager - context: schema.** Has permissions to assign roles to users in its schema. Can create/change/remove tables and columns (i.e., change the schema).

Based on this definition, it is expected that a user with the "manager" role should be able to update an existing schema. However, the following issue was encountered:

1. A user was created and assigned the "manager" role for a specific schema.
2. The schema was downloaded, modified (removing, adding, and updating schema elements), and attempted to be uploaded again.
3. The upload failed, producing errors, suggesting that the "manager" role does not have sufficient permissions to update the schema. 
4. The same issue occurs when attempting to update the schema via the schema editor, yielding the same error.

**Expected Behavior:**
A user with the "manager" role should be able to update an existing schema as described in the documentation.

**Actual Behavior:**
The user encounters errors when attempting to update the schema via both file upload and the schema editor.

A user from ERN CRANIO has reported this issue and provided error details, screenshot they send:

Image

Image

Image

### Reproduction steps

1. Create schema with template PATIENT_REGISTRY_DEMO
2. Create a user and assign the "manager" role to the created schema.
3. Download the schema.
4. Modify the schema (add/remove/update schema elements).
5. Login with the user with manager role
6. Upload modified schema to the create schema
7. Error

Image
Same happens when you change schema with schema editor.

### Expected behaviour

A user with the "manager" role should be able to update an existing schema as described in the documentation.

**Additional Context:**
This issue impacts schema management functionality and contradicts the documented permissions of the "manager" role.

**Suggested Fix:**
Investigate and ensure that the "manager" role has the appropriate permissions to update schemas as described in the documentation.

### System configuration

_No response_

### PR DESCRIPTION
**Pull request by harmbrugge**
Fixes #4894

### What are the main changes you did
- Added the manage role as owner of the trigger functions

### Todo:
- [x] add migration script?

### How to test
See issue #4894 

### Checklist
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

File: backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration26.sql [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+                n.nspname AS schema_name,
+                p.proname AS function_name,
+                pg_get_function_identity_arguments(p.oid) AS args
+            FROM
+                pg_proc p
+                    JOIN pg_namespace n ON p.pronamespace = n.oid
+                    JOIN pg_language l ON p.prolang = l.oid
+            WHERE
+                p.prorettype = 'pg_catalog.trigger'::regtype
+              AND n.nspname NOT IN ('pg_catalog', 'information_schema', '_SYSTEM_', 'MOLGENIS')
```
Comment (harmbrugge) [inline backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration26.sql:17]: Here I exclude the system schema's. I think this should cover it. Please review carefully. This worked for me locally.

**Review by mswertz — CHANGES_REQUESTED** [review]
small change, to not exclude _SYSTEM_

**Comment by harmbrugge** [comment]
> small change, to not exclude _SYSTEM_
Agreed.
>This might highlight other trigger functions that are not yet properly owned during creation? Did you check?
I did check all the trigger function that where updated; for me these where only the C_ and DEL_ functions addressed in this PR

**Review by Fernananas — APPROVED** [review]
Tested Scenarios:

Schema Editor (adjust schema):
✅ Works perfectly.

Upload via CSV – Add Column to Existing Table:
⚠️ Upload works, but the following validation error appears (same as with admin role):
Validation error (FieldUndefined@[DermatologistFollowUp/testAdd]) : Field 'testAdd' in type 'DermatologistFollowUp' is undefined
➤ Suggest reviewing how new fields are recognized during CSV-based schema updates.

Upload via CSV – Add New Table:
✅ Works perfectly.
