### PR TITLE
fix: datatime parsing failed for 2023-02-24T12:08:23.46378. closes #2100

### LINKED ISSUE #2100: Cannot upload data, cannot edit data in staging areas
**What version of EMX2 are you using (see footer)**
8.155.0

**Describe the bug**
When trying to upload data in zip into SharedStaging, I get an error: 'Text '2023-02-24T12:08:23.46378' could not be parsed, unparsed text found at index 23.'  This also happens when trying to edit a form on the dev server in schema called testCohort (a staging area). Pet store does not seem to have these issues, catalogue schema also not. 

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/'
2. Click on schema testCohort
3. Try to edit entry in table Cohorts and save
4. See error: Update into ...... failed. Transaction failed: Text '2023-02-24T12:08:23.46378' could not be parsed, unparsed text found at index 23

### PR DESCRIPTION
**Pull request by mswertz**

### CODE REVIEW

File: backend/molgenis-emx2/src/test/java/org/molgenis/emx2/TestTypeUtils.java [hunk 1]
```diff
@@ -63,4 +63,11 @@ public void testCommaInCsvString() {
     assertEquals("value with, comma", result[0]);
     assertEquals("and, another", result[1]);
   }
+
+  @Test
+  public void testDate() {
```
Comment (connoratrug) [inline backend/molgenis-emx2/src/test/java/org/molgenis/emx2/TestTypeUtils.java:68]: please add the reason for this test , what part /feature does it test , 'testDate' is to general is this test does not test the java Date object but rather s specific part of the string the string format

**Review by connoratrug — CHANGES_REQUESTED** [review]

**Review by connoratrug — APPROVED** [review]
